package model;

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * BaseJob definition.
 * 
 * This file was generated by Ignite Web Console (10/12/2020, 17:13)
 **/
public class BaseJob implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for jobName. */
    private String jobName;

    /** Value for departId. */
    private int departId;

    /** Value for parentId. */
    private String parentId;

    /** Value for maxCustomerNum. */
    private Integer maxCustomerNum;

    /** Value for noSensitiveFlag. */
    private Byte noSensitiveFlag;

    /** Value for jobType. */
    private String jobType;

    /** Value for delFlg. */
    private boolean delFlg;

    /** Value for createUser. */
    private int createUser;

    /** Value for createTime. */
    private Timestamp createTime;

    /** Value for updateTime. */
    private Timestamp updateTime;

    /** Value for updateUser. */
    private Integer updateUser;

    /** Value for highLayerFollowCount. */
    private Integer highLayerFollowCount;

    /** Empty constructor. **/
    public BaseJob() {
        // No-op.
    }

    /** Full constructor. **/
    public BaseJob(String jobName,
        int departId,
        String parentId,
        Integer maxCustomerNum,
        Byte noSensitiveFlag,
        String jobType,
        boolean delFlg,
        int createUser,
        Timestamp createTime,
        Timestamp updateTime,
        Integer updateUser,
        Integer highLayerFollowCount) {
        this.jobName = jobName;
        this.departId = departId;
        this.parentId = parentId;
        this.maxCustomerNum = maxCustomerNum;
        this.noSensitiveFlag = noSensitiveFlag;
        this.jobType = jobType;
        this.delFlg = delFlg;
        this.createUser = createUser;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.updateUser = updateUser;
        this.highLayerFollowCount = highLayerFollowCount;
    }

    /**
     * Gets jobName
     * 
     * @return Value for jobName.
     **/
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets jobName
     * 
     * @param jobName New value for jobName.
     **/
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * Gets departId
     * 
     * @return Value for departId.
     **/
    public int getDepartId() {
        return departId;
    }

    /**
     * Sets departId
     * 
     * @param departId New value for departId.
     **/
    public void setDepartId(int departId) {
        this.departId = departId;
    }

    /**
     * Gets parentId
     * 
     * @return Value for parentId.
     **/
    public String getParentId() {
        return parentId;
    }

    /**
     * Sets parentId
     * 
     * @param parentId New value for parentId.
     **/
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * Gets maxCustomerNum
     * 
     * @return Value for maxCustomerNum.
     **/
    public Integer getMaxCustomerNum() {
        return maxCustomerNum;
    }

    /**
     * Sets maxCustomerNum
     * 
     * @param maxCustomerNum New value for maxCustomerNum.
     **/
    public void setMaxCustomerNum(Integer maxCustomerNum) {
        this.maxCustomerNum = maxCustomerNum;
    }

    /**
     * Gets noSensitiveFlag
     * 
     * @return Value for noSensitiveFlag.
     **/
    public Byte getNoSensitiveFlag() {
        return noSensitiveFlag;
    }

    /**
     * Sets noSensitiveFlag
     * 
     * @param noSensitiveFlag New value for noSensitiveFlag.
     **/
    public void setNoSensitiveFlag(Byte noSensitiveFlag) {
        this.noSensitiveFlag = noSensitiveFlag;
    }

    /**
     * Gets jobType
     * 
     * @return Value for jobType.
     **/
    public String getJobType() {
        return jobType;
    }

    /**
     * Sets jobType
     * 
     * @param jobType New value for jobType.
     **/
    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    /**
     * Gets delFlg
     * 
     * @return Value for delFlg.
     **/
    public boolean getDelFlg() {
        return delFlg;
    }

    /**
     * Sets delFlg
     * 
     * @param delFlg New value for delFlg.
     **/
    public void setDelFlg(boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * Gets createUser
     * 
     * @return Value for createUser.
     **/
    public int getCreateUser() {
        return createUser;
    }

    /**
     * Sets createUser
     * 
     * @param createUser New value for createUser.
     **/
    public void setCreateUser(int createUser) {
        this.createUser = createUser;
    }

    /**
     * Gets createTime
     * 
     * @return Value for createTime.
     **/
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * Sets createTime
     * 
     * @param createTime New value for createTime.
     **/
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * Gets updateTime
     * 
     * @return Value for updateTime.
     **/
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets updateTime
     * 
     * @param updateTime New value for updateTime.
     **/
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Gets updateUser
     * 
     * @return Value for updateUser.
     **/
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * Sets updateUser
     * 
     * @param updateUser New value for updateUser.
     **/
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * Gets highLayerFollowCount
     * 
     * @return Value for highLayerFollowCount.
     **/
    public Integer getHighLayerFollowCount() {
        return highLayerFollowCount;
    }

    /**
     * Sets highLayerFollowCount
     * 
     * @param highLayerFollowCount New value for highLayerFollowCount.
     **/
    public void setHighLayerFollowCount(Integer highLayerFollowCount) {
        this.highLayerFollowCount = highLayerFollowCount;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof BaseJob))
            return false;
        
        BaseJob that = (BaseJob)o;

        if (jobName != null ? !jobName.equals(that.jobName) : that.jobName != null)
            return false;
        

        if (departId != that.departId)
            return false;
        

        if (parentId != null ? !parentId.equals(that.parentId) : that.parentId != null)
            return false;
        

        if (maxCustomerNum != null ? !maxCustomerNum.equals(that.maxCustomerNum) : that.maxCustomerNum != null)
            return false;
        

        if (noSensitiveFlag != null ? !noSensitiveFlag.equals(that.noSensitiveFlag) : that.noSensitiveFlag != null)
            return false;
        

        if (jobType != null ? !jobType.equals(that.jobType) : that.jobType != null)
            return false;
        

        if (delFlg != that.delFlg)
            return false;
        

        if (createUser != that.createUser)
            return false;
        

        if (createTime != null ? !createTime.equals(that.createTime) : that.createTime != null)
            return false;
        

        if (updateTime != null ? !updateTime.equals(that.updateTime) : that.updateTime != null)
            return false;
        

        if (updateUser != null ? !updateUser.equals(that.updateUser) : that.updateUser != null)
            return false;
        

        if (highLayerFollowCount != null ? !highLayerFollowCount.equals(that.highLayerFollowCount) : that.highLayerFollowCount != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = jobName != null ? jobName.hashCode() : 0;

        res = 31 * res + (departId);

        res = 31 * res + (parentId != null ? parentId.hashCode() : 0);

        res = 31 * res + (maxCustomerNum != null ? maxCustomerNum.hashCode() : 0);

        res = 31 * res + (noSensitiveFlag != null ? noSensitiveFlag.hashCode() : 0);

        res = 31 * res + (jobType != null ? jobType.hashCode() : 0);

        res = 31 * res + (delFlg ? 1 : 0);

        res = 31 * res + (createUser);

        res = 31 * res + (createTime != null ? createTime.hashCode() : 0);

        res = 31 * res + (updateTime != null ? updateTime.hashCode() : 0);

        res = 31 * res + (updateUser != null ? updateUser.hashCode() : 0);

        res = 31 * res + (highLayerFollowCount != null ? highLayerFollowCount.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "BaseJob [" + 
            "jobName=" + jobName + ", " + 
            "departId=" + departId + ", " + 
            "parentId=" + parentId + ", " + 
            "maxCustomerNum=" + maxCustomerNum + ", " + 
            "noSensitiveFlag=" + noSensitiveFlag + ", " + 
            "jobType=" + jobType + ", " + 
            "delFlg=" + delFlg + ", " + 
            "createUser=" + createUser + ", " + 
            "createTime=" + createTime + ", " + 
            "updateTime=" + updateTime + ", " + 
            "updateUser=" + updateUser + ", " + 
            "highLayerFollowCount=" + highLayerFollowCount +
        "]";
    }
}