package model;

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * BaseDepartment definition.
 * 
 * This file was generated by Ignite Web Console (10/12/2020, 17:13)
 **/
public class BaseDepartment implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for departName. */
    private String departName;

    /** Value for departType. */
    private String departType;

    /** Value for departAddress. */
    private String departAddress;

    /** Value for departPhone. */
    private String departPhone;

    /** Value for departCode. */
    private String departCode;

    /** Value for orgId. */
    private String orgId;

    /** Value for parentId. */
    private String parentId;

    /** Value for departProvince. */
    private Integer departProvince;

    /** Value for departCity. */
    private Integer departCity;

    /** Value for departDistrict. */
    private Integer departDistrict;

    /** Value for delFlg. */
    private boolean delFlg;

    /** Value for createTime. */
    private Timestamp createTime;

    /** Value for createUser. */
    private String createUser;

    /** Value for updateTime. */
    private Timestamp updateTime;

    /** Value for updateUser. */
    private String updateUser;

    /** Empty constructor. **/
    public BaseDepartment() {
        // No-op.
    }

    /** Full constructor. **/
    public BaseDepartment(String departName,
        String departType,
        String departAddress,
        String departPhone,
        String departCode,
        String orgId,
        String parentId,
        Integer departProvince,
        Integer departCity,
        Integer departDistrict,
        boolean delFlg,
        Timestamp createTime,
        String createUser,
        Timestamp updateTime,
        String updateUser) {
        this.departName = departName;
        this.departType = departType;
        this.departAddress = departAddress;
        this.departPhone = departPhone;
        this.departCode = departCode;
        this.orgId = orgId;
        this.parentId = parentId;
        this.departProvince = departProvince;
        this.departCity = departCity;
        this.departDistrict = departDistrict;
        this.delFlg = delFlg;
        this.createTime = createTime;
        this.createUser = createUser;
        this.updateTime = updateTime;
        this.updateUser = updateUser;
    }

    /**
     * Gets departName
     * 
     * @return Value for departName.
     **/
    public String getDepartName() {
        return departName;
    }

    /**
     * Sets departName
     * 
     * @param departName New value for departName.
     **/
    public void setDepartName(String departName) {
        this.departName = departName;
    }

    /**
     * Gets departType
     * 
     * @return Value for departType.
     **/
    public String getDepartType() {
        return departType;
    }

    /**
     * Sets departType
     * 
     * @param departType New value for departType.
     **/
    public void setDepartType(String departType) {
        this.departType = departType;
    }

    /**
     * Gets departAddress
     * 
     * @return Value for departAddress.
     **/
    public String getDepartAddress() {
        return departAddress;
    }

    /**
     * Sets departAddress
     * 
     * @param departAddress New value for departAddress.
     **/
    public void setDepartAddress(String departAddress) {
        this.departAddress = departAddress;
    }

    /**
     * Gets departPhone
     * 
     * @return Value for departPhone.
     **/
    public String getDepartPhone() {
        return departPhone;
    }

    /**
     * Sets departPhone
     * 
     * @param departPhone New value for departPhone.
     **/
    public void setDepartPhone(String departPhone) {
        this.departPhone = departPhone;
    }

    /**
     * Gets departCode
     * 
     * @return Value for departCode.
     **/
    public String getDepartCode() {
        return departCode;
    }

    /**
     * Sets departCode
     * 
     * @param departCode New value for departCode.
     **/
    public void setDepartCode(String departCode) {
        this.departCode = departCode;
    }

    /**
     * Gets orgId
     * 
     * @return Value for orgId.
     **/
    public String getOrgId() {
        return orgId;
    }

    /**
     * Sets orgId
     * 
     * @param orgId New value for orgId.
     **/
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    /**
     * Gets parentId
     * 
     * @return Value for parentId.
     **/
    public String getParentId() {
        return parentId;
    }

    /**
     * Sets parentId
     * 
     * @param parentId New value for parentId.
     **/
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * Gets departProvince
     * 
     * @return Value for departProvince.
     **/
    public Integer getDepartProvince() {
        return departProvince;
    }

    /**
     * Sets departProvince
     * 
     * @param departProvince New value for departProvince.
     **/
    public void setDepartProvince(Integer departProvince) {
        this.departProvince = departProvince;
    }

    /**
     * Gets departCity
     * 
     * @return Value for departCity.
     **/
    public Integer getDepartCity() {
        return departCity;
    }

    /**
     * Sets departCity
     * 
     * @param departCity New value for departCity.
     **/
    public void setDepartCity(Integer departCity) {
        this.departCity = departCity;
    }

    /**
     * Gets departDistrict
     * 
     * @return Value for departDistrict.
     **/
    public Integer getDepartDistrict() {
        return departDistrict;
    }

    /**
     * Sets departDistrict
     * 
     * @param departDistrict New value for departDistrict.
     **/
    public void setDepartDistrict(Integer departDistrict) {
        this.departDistrict = departDistrict;
    }

    /**
     * Gets delFlg
     * 
     * @return Value for delFlg.
     **/
    public boolean getDelFlg() {
        return delFlg;
    }

    /**
     * Sets delFlg
     * 
     * @param delFlg New value for delFlg.
     **/
    public void setDelFlg(boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * Gets createTime
     * 
     * @return Value for createTime.
     **/
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * Sets createTime
     * 
     * @param createTime New value for createTime.
     **/
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * Gets createUser
     * 
     * @return Value for createUser.
     **/
    public String getCreateUser() {
        return createUser;
    }

    /**
     * Sets createUser
     * 
     * @param createUser New value for createUser.
     **/
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * Gets updateTime
     * 
     * @return Value for updateTime.
     **/
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets updateTime
     * 
     * @param updateTime New value for updateTime.
     **/
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Gets updateUser
     * 
     * @return Value for updateUser.
     **/
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * Sets updateUser
     * 
     * @param updateUser New value for updateUser.
     **/
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof BaseDepartment))
            return false;
        
        BaseDepartment that = (BaseDepartment)o;

        if (departName != null ? !departName.equals(that.departName) : that.departName != null)
            return false;
        

        if (departType != null ? !departType.equals(that.departType) : that.departType != null)
            return false;
        

        if (departAddress != null ? !departAddress.equals(that.departAddress) : that.departAddress != null)
            return false;
        

        if (departPhone != null ? !departPhone.equals(that.departPhone) : that.departPhone != null)
            return false;
        

        if (departCode != null ? !departCode.equals(that.departCode) : that.departCode != null)
            return false;
        

        if (orgId != null ? !orgId.equals(that.orgId) : that.orgId != null)
            return false;
        

        if (parentId != null ? !parentId.equals(that.parentId) : that.parentId != null)
            return false;
        

        if (departProvince != null ? !departProvince.equals(that.departProvince) : that.departProvince != null)
            return false;
        

        if (departCity != null ? !departCity.equals(that.departCity) : that.departCity != null)
            return false;
        

        if (departDistrict != null ? !departDistrict.equals(that.departDistrict) : that.departDistrict != null)
            return false;
        

        if (delFlg != that.delFlg)
            return false;
        

        if (createTime != null ? !createTime.equals(that.createTime) : that.createTime != null)
            return false;
        

        if (createUser != null ? !createUser.equals(that.createUser) : that.createUser != null)
            return false;
        

        if (updateTime != null ? !updateTime.equals(that.updateTime) : that.updateTime != null)
            return false;
        

        if (updateUser != null ? !updateUser.equals(that.updateUser) : that.updateUser != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = departName != null ? departName.hashCode() : 0;

        res = 31 * res + (departType != null ? departType.hashCode() : 0);

        res = 31 * res + (departAddress != null ? departAddress.hashCode() : 0);

        res = 31 * res + (departPhone != null ? departPhone.hashCode() : 0);

        res = 31 * res + (departCode != null ? departCode.hashCode() : 0);

        res = 31 * res + (orgId != null ? orgId.hashCode() : 0);

        res = 31 * res + (parentId != null ? parentId.hashCode() : 0);

        res = 31 * res + (departProvince != null ? departProvince.hashCode() : 0);

        res = 31 * res + (departCity != null ? departCity.hashCode() : 0);

        res = 31 * res + (departDistrict != null ? departDistrict.hashCode() : 0);

        res = 31 * res + (delFlg ? 1 : 0);

        res = 31 * res + (createTime != null ? createTime.hashCode() : 0);

        res = 31 * res + (createUser != null ? createUser.hashCode() : 0);

        res = 31 * res + (updateTime != null ? updateTime.hashCode() : 0);

        res = 31 * res + (updateUser != null ? updateUser.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "BaseDepartment [" + 
            "departName=" + departName + ", " + 
            "departType=" + departType + ", " + 
            "departAddress=" + departAddress + ", " + 
            "departPhone=" + departPhone + ", " + 
            "departCode=" + departCode + ", " + 
            "orgId=" + orgId + ", " + 
            "parentId=" + parentId + ", " + 
            "departProvince=" + departProvince + ", " + 
            "departCity=" + departCity + ", " + 
            "departDistrict=" + departDistrict + ", " + 
            "delFlg=" + delFlg + ", " + 
            "createTime=" + createTime + ", " + 
            "createUser=" + createUser + ", " + 
            "updateTime=" + updateTime + ", " + 
            "updateUser=" + updateUser +
        "]";
    }
}