package model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Business definition.
 * 
 * This file was generated by Ignite Web Console (10/12/2020, 17:13)
 **/
public class Business implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for customerId. */
    private int customerId;

    /** Value for name. */
    private String name;

    /** Value for modifyName. */
    private String modifyName;

    /** Value for businessCode. */
    private String businessCode;

    /** Value for origin. */
    private String origin;

    /** Value for description. */
    private String description;

    /** Value for level. */
    private String level;

    /** Value for industryLevelOne. */
    private String industryLevelOne;

    /** Value for industryLevelTwo. */
    private String industryLevelTwo;

    /** Value for phaseOneCompleteTime. */
    private Timestamp phaseOneCompleteTime;

    /** Value for phaseTwoCompleteTime. */
    private Timestamp phaseTwoCompleteTime;

    /** Value for phaseThreeCompleteTime. */
    private Timestamp phaseThreeCompleteTime;

    /** Value for phaseFourCompleteTime. */
    private Timestamp phaseFourCompleteTime;

    /** Value for phase. */
    private Byte phase;

    /** Value for businessStatus. */
    private byte businessStatus;

    /** Value for restartStatus. */
    private Boolean restartStatus;

    /** Value for expectAmount. */
    private BigDecimal expectAmount;

    /** Value for expectTime. */
    private Timestamp expectTime;

    /** Value for expectMedia. */
    private String expectMedia;

    /** Value for expectCity. */
    private String expectCity;

    /** Value for expectNum. */
    private Integer expectNum;

    /** Value for expectFrequency. */
    private String expectFrequency;

    /** Value for actualNum. */
    private Integer actualNum;

    /** Value for actualFrequency. */
    private String actualFrequency;

    /** Value for mediaAttitude. */
    private String mediaAttitude;

    /** Value for belongUserId. */
    private Integer belongUserId;

    /** Value for createUser. */
    private Integer createUser;

    /** Value for createTime. */
    private Timestamp createTime;

    /** Value for updateUser. */
    private Integer updateUser;

    /** Value for updateTime. */
    private Timestamp updateTime;

    /** Value for remark. */
    private String remark;

    /** Value for failReason. */
    private String failReason;

    /** Value for closeReason. */
    private String closeReason;

    /** Value for acceptProposalFlag. */
    private Boolean acceptProposalFlag;

    /** Value for acceptQuoteFlag. */
    private Boolean acceptQuoteFlag;

    /** Value for communicateMaterialFlag. */
    private Boolean communicateMaterialFlag;

    /** Value for comfirmPlanFlag. */
    private Boolean comfirmPlanFlag;

    /** Value for comfirmMaterialFlag. */
    private Boolean comfirmMaterialFlag;

    /** Value for jobId. */
    private Integer jobId;

    /** Value for orgId. */
    private Integer orgId;

    /** Value for departId. */
    private Integer departId;

    /** Value for proposalCustomerFlag. */
    private Boolean proposalCustomerFlag;

    /** Value for confirmPointFlag. */
    private Boolean confirmPointFlag;

    /** Value for preSignContractDate. */
    private Timestamp preSignContractDate;

    /** Value for contractTakeBackDate. */
    private Timestamp contractTakeBackDate;

    /** Value for contractTakeBackFlag. */
    private Boolean contractTakeBackFlag;

    /** Value for issueFlag. */
    private Boolean issueFlag;

    /** Value for businessLevel. */
    private String businessLevel;

    /** Value for accompanyNum. */
    private Integer accompanyNum;

    /** Value for syncSys. */
    private Boolean syncSys;

    /** Value for dealAmount. */
    private BigDecimal dealAmount;

    /** Value for dealTime. */
    private Timestamp dealTime;

    /** Value for onlineDate. */
    private Timestamp onlineDate;

    /** Value for offlineDate. */
    private Timestamp offlineDate;

    /** Value for closeTime. */
    private Timestamp closeTime;

    /** Value for businessType. */
    private String businessType;

    /** Value for contractSigningType. */
    private String contractSigningType;

    /** Value for mediaRecognized. */
    private boolean mediaRecognized;

    /** Value for hasBudget. */
    private boolean hasBudget;

    /** Value for hasLaunchPlan. */
    private boolean hasLaunchPlan;

    /** Value for kpVisited. */
    private boolean kpVisited;

    /** Value for launchCityPointConfirmed. */
    private boolean launchCityPointConfirmed;

    /** Value for materialConfirmed. */
    private boolean materialConfirmed;

    /** Value for processingContract. */
    private boolean processingContract;

    /** Value for priceDiscount. */
    private BigDecimal priceDiscount;

    /** Value for priceDiscountRatio. */
    private BigDecimal priceDiscountRatio;

    /** Value for priceDiscountTime. */
    private Timestamp priceDiscountTime;

    /** Value for quoteDiscount. */
    private BigDecimal quoteDiscount;

    /** Value for quoteDiscountRatio. */
    private BigDecimal quoteDiscountRatio;

    /** Value for quoteDiscountTime. */
    private Timestamp quoteDiscountTime;

    /** Value for businessOpportunityType. */
    private String businessOpportunityType;

    /** Value for dealResource. */
    private String dealResource;

    /** Value for discount. */
    private BigDecimal discount;

    /** Value for zhitouFlag. */
    private Boolean zhitouFlag;

    /** Value for zhitouPlanFlag. */
    private Boolean zhitouPlanFlag;

    /** Value for zhitouPlanId. */
    private Integer zhitouPlanId;

    /** Value for closeReasonType. */
    private String closeReasonType;

    /** Value for pushFlag. */
    private Boolean pushFlag;

    /** Empty constructor. **/
    public Business() {
        // No-op.
    }

    /** Full constructor. **/
    public Business(int customerId,
        String name,
        String modifyName,
        String businessCode,
        String origin,
        String description,
        String level,
        String industryLevelOne,
        String industryLevelTwo,
        Timestamp phaseOneCompleteTime,
        Timestamp phaseTwoCompleteTime,
        Timestamp phaseThreeCompleteTime,
        Timestamp phaseFourCompleteTime,
        Byte phase,
        byte businessStatus,
        Boolean restartStatus,
        BigDecimal expectAmount,
        Timestamp expectTime,
        String expectMedia,
        String expectCity,
        Integer expectNum,
        String expectFrequency,
        Integer actualNum,
        String actualFrequency,
        String mediaAttitude,
        Integer belongUserId,
        Integer createUser,
        Timestamp createTime,
        Integer updateUser,
        Timestamp updateTime,
        String remark,
        String failReason,
        String closeReason,
        Boolean acceptProposalFlag,
        Boolean acceptQuoteFlag,
        Boolean communicateMaterialFlag,
        Boolean comfirmPlanFlag,
        Boolean comfirmMaterialFlag,
        Integer jobId,
        Integer orgId,
        Integer departId,
        Boolean proposalCustomerFlag,
        Boolean confirmPointFlag,
        Timestamp preSignContractDate,
        Timestamp contractTakeBackDate,
        Boolean contractTakeBackFlag,
        Boolean issueFlag,
        String businessLevel,
        Integer accompanyNum,
        Boolean syncSys,
        BigDecimal dealAmount,
        Timestamp dealTime,
        Timestamp onlineDate,
        Timestamp offlineDate,
        Timestamp closeTime,
        String businessType,
        String contractSigningType,
        boolean mediaRecognized,
        boolean hasBudget,
        boolean hasLaunchPlan,
        boolean kpVisited,
        boolean launchCityPointConfirmed,
        boolean materialConfirmed,
        boolean processingContract,
        BigDecimal priceDiscount,
        BigDecimal priceDiscountRatio,
        Timestamp priceDiscountTime,
        BigDecimal quoteDiscount,
        BigDecimal quoteDiscountRatio,
        Timestamp quoteDiscountTime,
        String businessOpportunityType,
        String dealResource,
        BigDecimal discount,
        Boolean zhitouFlag,
        Boolean zhitouPlanFlag,
        Integer zhitouPlanId,
        String closeReasonType,
        Boolean pushFlag) {
        this.customerId = customerId;
        this.name = name;
        this.modifyName = modifyName;
        this.businessCode = businessCode;
        this.origin = origin;
        this.description = description;
        this.level = level;
        this.industryLevelOne = industryLevelOne;
        this.industryLevelTwo = industryLevelTwo;
        this.phaseOneCompleteTime = phaseOneCompleteTime;
        this.phaseTwoCompleteTime = phaseTwoCompleteTime;
        this.phaseThreeCompleteTime = phaseThreeCompleteTime;
        this.phaseFourCompleteTime = phaseFourCompleteTime;
        this.phase = phase;
        this.businessStatus = businessStatus;
        this.restartStatus = restartStatus;
        this.expectAmount = expectAmount;
        this.expectTime = expectTime;
        this.expectMedia = expectMedia;
        this.expectCity = expectCity;
        this.expectNum = expectNum;
        this.expectFrequency = expectFrequency;
        this.actualNum = actualNum;
        this.actualFrequency = actualFrequency;
        this.mediaAttitude = mediaAttitude;
        this.belongUserId = belongUserId;
        this.createUser = createUser;
        this.createTime = createTime;
        this.updateUser = updateUser;
        this.updateTime = updateTime;
        this.remark = remark;
        this.failReason = failReason;
        this.closeReason = closeReason;
        this.acceptProposalFlag = acceptProposalFlag;
        this.acceptQuoteFlag = acceptQuoteFlag;
        this.communicateMaterialFlag = communicateMaterialFlag;
        this.comfirmPlanFlag = comfirmPlanFlag;
        this.comfirmMaterialFlag = comfirmMaterialFlag;
        this.jobId = jobId;
        this.orgId = orgId;
        this.departId = departId;
        this.proposalCustomerFlag = proposalCustomerFlag;
        this.confirmPointFlag = confirmPointFlag;
        this.preSignContractDate = preSignContractDate;
        this.contractTakeBackDate = contractTakeBackDate;
        this.contractTakeBackFlag = contractTakeBackFlag;
        this.issueFlag = issueFlag;
        this.businessLevel = businessLevel;
        this.accompanyNum = accompanyNum;
        this.syncSys = syncSys;
        this.dealAmount = dealAmount;
        this.dealTime = dealTime;
        this.onlineDate = onlineDate;
        this.offlineDate = offlineDate;
        this.closeTime = closeTime;
        this.businessType = businessType;
        this.contractSigningType = contractSigningType;
        this.mediaRecognized = mediaRecognized;
        this.hasBudget = hasBudget;
        this.hasLaunchPlan = hasLaunchPlan;
        this.kpVisited = kpVisited;
        this.launchCityPointConfirmed = launchCityPointConfirmed;
        this.materialConfirmed = materialConfirmed;
        this.processingContract = processingContract;
        this.priceDiscount = priceDiscount;
        this.priceDiscountRatio = priceDiscountRatio;
        this.priceDiscountTime = priceDiscountTime;
        this.quoteDiscount = quoteDiscount;
        this.quoteDiscountRatio = quoteDiscountRatio;
        this.quoteDiscountTime = quoteDiscountTime;
        this.businessOpportunityType = businessOpportunityType;
        this.dealResource = dealResource;
        this.discount = discount;
        this.zhitouFlag = zhitouFlag;
        this.zhitouPlanFlag = zhitouPlanFlag;
        this.zhitouPlanId = zhitouPlanId;
        this.closeReasonType = closeReasonType;
        this.pushFlag = pushFlag;
    }

    /**
     * Gets customerId
     * 
     * @return Value for customerId.
     **/
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Sets customerId
     * 
     * @param customerId New value for customerId.
     **/
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets modifyName
     * 
     * @return Value for modifyName.
     **/
    public String getModifyName() {
        return modifyName;
    }

    /**
     * Sets modifyName
     * 
     * @param modifyName New value for modifyName.
     **/
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName;
    }

    /**
     * Gets businessCode
     * 
     * @return Value for businessCode.
     **/
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * Sets businessCode
     * 
     * @param businessCode New value for businessCode.
     **/
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * Gets origin
     * 
     * @return Value for origin.
     **/
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets origin
     * 
     * @param origin New value for origin.
     **/
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets level
     * 
     * @return Value for level.
     **/
    public String getLevel() {
        return level;
    }

    /**
     * Sets level
     * 
     * @param level New value for level.
     **/
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * Gets industryLevelOne
     * 
     * @return Value for industryLevelOne.
     **/
    public String getIndustryLevelOne() {
        return industryLevelOne;
    }

    /**
     * Sets industryLevelOne
     * 
     * @param industryLevelOne New value for industryLevelOne.
     **/
    public void setIndustryLevelOne(String industryLevelOne) {
        this.industryLevelOne = industryLevelOne;
    }

    /**
     * Gets industryLevelTwo
     * 
     * @return Value for industryLevelTwo.
     **/
    public String getIndustryLevelTwo() {
        return industryLevelTwo;
    }

    /**
     * Sets industryLevelTwo
     * 
     * @param industryLevelTwo New value for industryLevelTwo.
     **/
    public void setIndustryLevelTwo(String industryLevelTwo) {
        this.industryLevelTwo = industryLevelTwo;
    }

    /**
     * Gets phaseOneCompleteTime
     * 
     * @return Value for phaseOneCompleteTime.
     **/
    public Timestamp getPhaseOneCompleteTime() {
        return phaseOneCompleteTime;
    }

    /**
     * Sets phaseOneCompleteTime
     * 
     * @param phaseOneCompleteTime New value for phaseOneCompleteTime.
     **/
    public void setPhaseOneCompleteTime(Timestamp phaseOneCompleteTime) {
        this.phaseOneCompleteTime = phaseOneCompleteTime;
    }

    /**
     * Gets phaseTwoCompleteTime
     * 
     * @return Value for phaseTwoCompleteTime.
     **/
    public Timestamp getPhaseTwoCompleteTime() {
        return phaseTwoCompleteTime;
    }

    /**
     * Sets phaseTwoCompleteTime
     * 
     * @param phaseTwoCompleteTime New value for phaseTwoCompleteTime.
     **/
    public void setPhaseTwoCompleteTime(Timestamp phaseTwoCompleteTime) {
        this.phaseTwoCompleteTime = phaseTwoCompleteTime;
    }

    /**
     * Gets phaseThreeCompleteTime
     * 
     * @return Value for phaseThreeCompleteTime.
     **/
    public Timestamp getPhaseThreeCompleteTime() {
        return phaseThreeCompleteTime;
    }

    /**
     * Sets phaseThreeCompleteTime
     * 
     * @param phaseThreeCompleteTime New value for phaseThreeCompleteTime.
     **/
    public void setPhaseThreeCompleteTime(Timestamp phaseThreeCompleteTime) {
        this.phaseThreeCompleteTime = phaseThreeCompleteTime;
    }

    /**
     * Gets phaseFourCompleteTime
     * 
     * @return Value for phaseFourCompleteTime.
     **/
    public Timestamp getPhaseFourCompleteTime() {
        return phaseFourCompleteTime;
    }

    /**
     * Sets phaseFourCompleteTime
     * 
     * @param phaseFourCompleteTime New value for phaseFourCompleteTime.
     **/
    public void setPhaseFourCompleteTime(Timestamp phaseFourCompleteTime) {
        this.phaseFourCompleteTime = phaseFourCompleteTime;
    }

    /**
     * Gets phase
     * 
     * @return Value for phase.
     **/
    public Byte getPhase() {
        return phase;
    }

    /**
     * Sets phase
     * 
     * @param phase New value for phase.
     **/
    public void setPhase(Byte phase) {
        this.phase = phase;
    }

    /**
     * Gets businessStatus
     * 
     * @return Value for businessStatus.
     **/
    public byte getBusinessStatus() {
        return businessStatus;
    }

    /**
     * Sets businessStatus
     * 
     * @param businessStatus New value for businessStatus.
     **/
    public void setBusinessStatus(byte businessStatus) {
        this.businessStatus = businessStatus;
    }

    /**
     * Gets restartStatus
     * 
     * @return Value for restartStatus.
     **/
    public Boolean getRestartStatus() {
        return restartStatus;
    }

    /**
     * Sets restartStatus
     * 
     * @param restartStatus New value for restartStatus.
     **/
    public void setRestartStatus(Boolean restartStatus) {
        this.restartStatus = restartStatus;
    }

    /**
     * Gets expectAmount
     * 
     * @return Value for expectAmount.
     **/
    public BigDecimal getExpectAmount() {
        return expectAmount;
    }

    /**
     * Sets expectAmount
     * 
     * @param expectAmount New value for expectAmount.
     **/
    public void setExpectAmount(BigDecimal expectAmount) {
        this.expectAmount = expectAmount;
    }

    /**
     * Gets expectTime
     * 
     * @return Value for expectTime.
     **/
    public Timestamp getExpectTime() {
        return expectTime;
    }

    /**
     * Sets expectTime
     * 
     * @param expectTime New value for expectTime.
     **/
    public void setExpectTime(Timestamp expectTime) {
        this.expectTime = expectTime;
    }

    /**
     * Gets expectMedia
     * 
     * @return Value for expectMedia.
     **/
    public String getExpectMedia() {
        return expectMedia;
    }

    /**
     * Sets expectMedia
     * 
     * @param expectMedia New value for expectMedia.
     **/
    public void setExpectMedia(String expectMedia) {
        this.expectMedia = expectMedia;
    }

    /**
     * Gets expectCity
     * 
     * @return Value for expectCity.
     **/
    public String getExpectCity() {
        return expectCity;
    }

    /**
     * Sets expectCity
     * 
     * @param expectCity New value for expectCity.
     **/
    public void setExpectCity(String expectCity) {
        this.expectCity = expectCity;
    }

    /**
     * Gets expectNum
     * 
     * @return Value for expectNum.
     **/
    public Integer getExpectNum() {
        return expectNum;
    }

    /**
     * Sets expectNum
     * 
     * @param expectNum New value for expectNum.
     **/
    public void setExpectNum(Integer expectNum) {
        this.expectNum = expectNum;
    }

    /**
     * Gets expectFrequency
     * 
     * @return Value for expectFrequency.
     **/
    public String getExpectFrequency() {
        return expectFrequency;
    }

    /**
     * Sets expectFrequency
     * 
     * @param expectFrequency New value for expectFrequency.
     **/
    public void setExpectFrequency(String expectFrequency) {
        this.expectFrequency = expectFrequency;
    }

    /**
     * Gets actualNum
     * 
     * @return Value for actualNum.
     **/
    public Integer getActualNum() {
        return actualNum;
    }

    /**
     * Sets actualNum
     * 
     * @param actualNum New value for actualNum.
     **/
    public void setActualNum(Integer actualNum) {
        this.actualNum = actualNum;
    }

    /**
     * Gets actualFrequency
     * 
     * @return Value for actualFrequency.
     **/
    public String getActualFrequency() {
        return actualFrequency;
    }

    /**
     * Sets actualFrequency
     * 
     * @param actualFrequency New value for actualFrequency.
     **/
    public void setActualFrequency(String actualFrequency) {
        this.actualFrequency = actualFrequency;
    }

    /**
     * Gets mediaAttitude
     * 
     * @return Value for mediaAttitude.
     **/
    public String getMediaAttitude() {
        return mediaAttitude;
    }

    /**
     * Sets mediaAttitude
     * 
     * @param mediaAttitude New value for mediaAttitude.
     **/
    public void setMediaAttitude(String mediaAttitude) {
        this.mediaAttitude = mediaAttitude;
    }

    /**
     * Gets belongUserId
     * 
     * @return Value for belongUserId.
     **/
    public Integer getBelongUserId() {
        return belongUserId;
    }

    /**
     * Sets belongUserId
     * 
     * @param belongUserId New value for belongUserId.
     **/
    public void setBelongUserId(Integer belongUserId) {
        this.belongUserId = belongUserId;
    }

    /**
     * Gets createUser
     * 
     * @return Value for createUser.
     **/
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * Sets createUser
     * 
     * @param createUser New value for createUser.
     **/
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * Gets createTime
     * 
     * @return Value for createTime.
     **/
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * Sets createTime
     * 
     * @param createTime New value for createTime.
     **/
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * Gets updateUser
     * 
     * @return Value for updateUser.
     **/
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * Sets updateUser
     * 
     * @param updateUser New value for updateUser.
     **/
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * Gets updateTime
     * 
     * @return Value for updateTime.
     **/
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets updateTime
     * 
     * @param updateTime New value for updateTime.
     **/
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Gets remark
     * 
     * @return Value for remark.
     **/
    public String getRemark() {
        return remark;
    }

    /**
     * Sets remark
     * 
     * @param remark New value for remark.
     **/
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * Gets failReason
     * 
     * @return Value for failReason.
     **/
    public String getFailReason() {
        return failReason;
    }

    /**
     * Sets failReason
     * 
     * @param failReason New value for failReason.
     **/
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }

    /**
     * Gets closeReason
     * 
     * @return Value for closeReason.
     **/
    public String getCloseReason() {
        return closeReason;
    }

    /**
     * Sets closeReason
     * 
     * @param closeReason New value for closeReason.
     **/
    public void setCloseReason(String closeReason) {
        this.closeReason = closeReason;
    }

    /**
     * Gets acceptProposalFlag
     * 
     * @return Value for acceptProposalFlag.
     **/
    public Boolean getAcceptProposalFlag() {
        return acceptProposalFlag;
    }

    /**
     * Sets acceptProposalFlag
     * 
     * @param acceptProposalFlag New value for acceptProposalFlag.
     **/
    public void setAcceptProposalFlag(Boolean acceptProposalFlag) {
        this.acceptProposalFlag = acceptProposalFlag;
    }

    /**
     * Gets acceptQuoteFlag
     * 
     * @return Value for acceptQuoteFlag.
     **/
    public Boolean getAcceptQuoteFlag() {
        return acceptQuoteFlag;
    }

    /**
     * Sets acceptQuoteFlag
     * 
     * @param acceptQuoteFlag New value for acceptQuoteFlag.
     **/
    public void setAcceptQuoteFlag(Boolean acceptQuoteFlag) {
        this.acceptQuoteFlag = acceptQuoteFlag;
    }

    /**
     * Gets communicateMaterialFlag
     * 
     * @return Value for communicateMaterialFlag.
     **/
    public Boolean getCommunicateMaterialFlag() {
        return communicateMaterialFlag;
    }

    /**
     * Sets communicateMaterialFlag
     * 
     * @param communicateMaterialFlag New value for communicateMaterialFlag.
     **/
    public void setCommunicateMaterialFlag(Boolean communicateMaterialFlag) {
        this.communicateMaterialFlag = communicateMaterialFlag;
    }

    /**
     * Gets comfirmPlanFlag
     * 
     * @return Value for comfirmPlanFlag.
     **/
    public Boolean getComfirmPlanFlag() {
        return comfirmPlanFlag;
    }

    /**
     * Sets comfirmPlanFlag
     * 
     * @param comfirmPlanFlag New value for comfirmPlanFlag.
     **/
    public void setComfirmPlanFlag(Boolean comfirmPlanFlag) {
        this.comfirmPlanFlag = comfirmPlanFlag;
    }

    /**
     * Gets comfirmMaterialFlag
     * 
     * @return Value for comfirmMaterialFlag.
     **/
    public Boolean getComfirmMaterialFlag() {
        return comfirmMaterialFlag;
    }

    /**
     * Sets comfirmMaterialFlag
     * 
     * @param comfirmMaterialFlag New value for comfirmMaterialFlag.
     **/
    public void setComfirmMaterialFlag(Boolean comfirmMaterialFlag) {
        this.comfirmMaterialFlag = comfirmMaterialFlag;
    }

    /**
     * Gets jobId
     * 
     * @return Value for jobId.
     **/
    public Integer getJobId() {
        return jobId;
    }

    /**
     * Sets jobId
     * 
     * @param jobId New value for jobId.
     **/
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * Gets orgId
     * 
     * @return Value for orgId.
     **/
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * Sets orgId
     * 
     * @param orgId New value for orgId.
     **/
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * Gets departId
     * 
     * @return Value for departId.
     **/
    public Integer getDepartId() {
        return departId;
    }

    /**
     * Sets departId
     * 
     * @param departId New value for departId.
     **/
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * Gets proposalCustomerFlag
     * 
     * @return Value for proposalCustomerFlag.
     **/
    public Boolean getProposalCustomerFlag() {
        return proposalCustomerFlag;
    }

    /**
     * Sets proposalCustomerFlag
     * 
     * @param proposalCustomerFlag New value for proposalCustomerFlag.
     **/
    public void setProposalCustomerFlag(Boolean proposalCustomerFlag) {
        this.proposalCustomerFlag = proposalCustomerFlag;
    }

    /**
     * Gets confirmPointFlag
     * 
     * @return Value for confirmPointFlag.
     **/
    public Boolean getConfirmPointFlag() {
        return confirmPointFlag;
    }

    /**
     * Sets confirmPointFlag
     * 
     * @param confirmPointFlag New value for confirmPointFlag.
     **/
    public void setConfirmPointFlag(Boolean confirmPointFlag) {
        this.confirmPointFlag = confirmPointFlag;
    }

    /**
     * Gets preSignContractDate
     * 
     * @return Value for preSignContractDate.
     **/
    public Timestamp getPreSignContractDate() {
        return preSignContractDate;
    }

    /**
     * Sets preSignContractDate
     * 
     * @param preSignContractDate New value for preSignContractDate.
     **/
    public void setPreSignContractDate(Timestamp preSignContractDate) {
        this.preSignContractDate = preSignContractDate;
    }

    /**
     * Gets contractTakeBackDate
     * 
     * @return Value for contractTakeBackDate.
     **/
    public Timestamp getContractTakeBackDate() {
        return contractTakeBackDate;
    }

    /**
     * Sets contractTakeBackDate
     * 
     * @param contractTakeBackDate New value for contractTakeBackDate.
     **/
    public void setContractTakeBackDate(Timestamp contractTakeBackDate) {
        this.contractTakeBackDate = contractTakeBackDate;
    }

    /**
     * Gets contractTakeBackFlag
     * 
     * @return Value for contractTakeBackFlag.
     **/
    public Boolean getContractTakeBackFlag() {
        return contractTakeBackFlag;
    }

    /**
     * Sets contractTakeBackFlag
     * 
     * @param contractTakeBackFlag New value for contractTakeBackFlag.
     **/
    public void setContractTakeBackFlag(Boolean contractTakeBackFlag) {
        this.contractTakeBackFlag = contractTakeBackFlag;
    }

    /**
     * Gets issueFlag
     * 
     * @return Value for issueFlag.
     **/
    public Boolean getIssueFlag() {
        return issueFlag;
    }

    /**
     * Sets issueFlag
     * 
     * @param issueFlag New value for issueFlag.
     **/
    public void setIssueFlag(Boolean issueFlag) {
        this.issueFlag = issueFlag;
    }

    /**
     * Gets businessLevel
     * 
     * @return Value for businessLevel.
     **/
    public String getBusinessLevel() {
        return businessLevel;
    }

    /**
     * Sets businessLevel
     * 
     * @param businessLevel New value for businessLevel.
     **/
    public void setBusinessLevel(String businessLevel) {
        this.businessLevel = businessLevel;
    }

    /**
     * Gets accompanyNum
     * 
     * @return Value for accompanyNum.
     **/
    public Integer getAccompanyNum() {
        return accompanyNum;
    }

    /**
     * Sets accompanyNum
     * 
     * @param accompanyNum New value for accompanyNum.
     **/
    public void setAccompanyNum(Integer accompanyNum) {
        this.accompanyNum = accompanyNum;
    }

    /**
     * Gets syncSys
     * 
     * @return Value for syncSys.
     **/
    public Boolean getSyncSys() {
        return syncSys;
    }

    /**
     * Sets syncSys
     * 
     * @param syncSys New value for syncSys.
     **/
    public void setSyncSys(Boolean syncSys) {
        this.syncSys = syncSys;
    }

    /**
     * Gets dealAmount
     * 
     * @return Value for dealAmount.
     **/
    public BigDecimal getDealAmount() {
        return dealAmount;
    }

    /**
     * Sets dealAmount
     * 
     * @param dealAmount New value for dealAmount.
     **/
    public void setDealAmount(BigDecimal dealAmount) {
        this.dealAmount = dealAmount;
    }

    /**
     * Gets dealTime
     * 
     * @return Value for dealTime.
     **/
    public Timestamp getDealTime() {
        return dealTime;
    }

    /**
     * Sets dealTime
     * 
     * @param dealTime New value for dealTime.
     **/
    public void setDealTime(Timestamp dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * Gets onlineDate
     * 
     * @return Value for onlineDate.
     **/
    public Timestamp getOnlineDate() {
        return onlineDate;
    }

    /**
     * Sets onlineDate
     * 
     * @param onlineDate New value for onlineDate.
     **/
    public void setOnlineDate(Timestamp onlineDate) {
        this.onlineDate = onlineDate;
    }

    /**
     * Gets offlineDate
     * 
     * @return Value for offlineDate.
     **/
    public Timestamp getOfflineDate() {
        return offlineDate;
    }

    /**
     * Sets offlineDate
     * 
     * @param offlineDate New value for offlineDate.
     **/
    public void setOfflineDate(Timestamp offlineDate) {
        this.offlineDate = offlineDate;
    }

    /**
     * Gets closeTime
     * 
     * @return Value for closeTime.
     **/
    public Timestamp getCloseTime() {
        return closeTime;
    }

    /**
     * Sets closeTime
     * 
     * @param closeTime New value for closeTime.
     **/
    public void setCloseTime(Timestamp closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * Gets businessType
     * 
     * @return Value for businessType.
     **/
    public String getBusinessType() {
        return businessType;
    }

    /**
     * Sets businessType
     * 
     * @param businessType New value for businessType.
     **/
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * Gets contractSigningType
     * 
     * @return Value for contractSigningType.
     **/
    public String getContractSigningType() {
        return contractSigningType;
    }

    /**
     * Sets contractSigningType
     * 
     * @param contractSigningType New value for contractSigningType.
     **/
    public void setContractSigningType(String contractSigningType) {
        this.contractSigningType = contractSigningType;
    }

    /**
     * Gets mediaRecognized
     * 
     * @return Value for mediaRecognized.
     **/
    public boolean getMediaRecognized() {
        return mediaRecognized;
    }

    /**
     * Sets mediaRecognized
     * 
     * @param mediaRecognized New value for mediaRecognized.
     **/
    public void setMediaRecognized(boolean mediaRecognized) {
        this.mediaRecognized = mediaRecognized;
    }

    /**
     * Gets hasBudget
     * 
     * @return Value for hasBudget.
     **/
    public boolean getHasBudget() {
        return hasBudget;
    }

    /**
     * Sets hasBudget
     * 
     * @param hasBudget New value for hasBudget.
     **/
    public void setHasBudget(boolean hasBudget) {
        this.hasBudget = hasBudget;
    }

    /**
     * Gets hasLaunchPlan
     * 
     * @return Value for hasLaunchPlan.
     **/
    public boolean getHasLaunchPlan() {
        return hasLaunchPlan;
    }

    /**
     * Sets hasLaunchPlan
     * 
     * @param hasLaunchPlan New value for hasLaunchPlan.
     **/
    public void setHasLaunchPlan(boolean hasLaunchPlan) {
        this.hasLaunchPlan = hasLaunchPlan;
    }

    /**
     * Gets kpVisited
     * 
     * @return Value for kpVisited.
     **/
    public boolean getKpVisited() {
        return kpVisited;
    }

    /**
     * Sets kpVisited
     * 
     * @param kpVisited New value for kpVisited.
     **/
    public void setKpVisited(boolean kpVisited) {
        this.kpVisited = kpVisited;
    }

    /**
     * Gets launchCityPointConfirmed
     * 
     * @return Value for launchCityPointConfirmed.
     **/
    public boolean getLaunchCityPointConfirmed() {
        return launchCityPointConfirmed;
    }

    /**
     * Sets launchCityPointConfirmed
     * 
     * @param launchCityPointConfirmed New value for launchCityPointConfirmed.
     **/
    public void setLaunchCityPointConfirmed(boolean launchCityPointConfirmed) {
        this.launchCityPointConfirmed = launchCityPointConfirmed;
    }

    /**
     * Gets materialConfirmed
     * 
     * @return Value for materialConfirmed.
     **/
    public boolean getMaterialConfirmed() {
        return materialConfirmed;
    }

    /**
     * Sets materialConfirmed
     * 
     * @param materialConfirmed New value for materialConfirmed.
     **/
    public void setMaterialConfirmed(boolean materialConfirmed) {
        this.materialConfirmed = materialConfirmed;
    }

    /**
     * Gets processingContract
     * 
     * @return Value for processingContract.
     **/
    public boolean getProcessingContract() {
        return processingContract;
    }

    /**
     * Sets processingContract
     * 
     * @param processingContract New value for processingContract.
     **/
    public void setProcessingContract(boolean processingContract) {
        this.processingContract = processingContract;
    }

    /**
     * Gets priceDiscount
     * 
     * @return Value for priceDiscount.
     **/
    public BigDecimal getPriceDiscount() {
        return priceDiscount;
    }

    /**
     * Sets priceDiscount
     * 
     * @param priceDiscount New value for priceDiscount.
     **/
    public void setPriceDiscount(BigDecimal priceDiscount) {
        this.priceDiscount = priceDiscount;
    }

    /**
     * Gets priceDiscountRatio
     * 
     * @return Value for priceDiscountRatio.
     **/
    public BigDecimal getPriceDiscountRatio() {
        return priceDiscountRatio;
    }

    /**
     * Sets priceDiscountRatio
     * 
     * @param priceDiscountRatio New value for priceDiscountRatio.
     **/
    public void setPriceDiscountRatio(BigDecimal priceDiscountRatio) {
        this.priceDiscountRatio = priceDiscountRatio;
    }

    /**
     * Gets priceDiscountTime
     * 
     * @return Value for priceDiscountTime.
     **/
    public Timestamp getPriceDiscountTime() {
        return priceDiscountTime;
    }

    /**
     * Sets priceDiscountTime
     * 
     * @param priceDiscountTime New value for priceDiscountTime.
     **/
    public void setPriceDiscountTime(Timestamp priceDiscountTime) {
        this.priceDiscountTime = priceDiscountTime;
    }

    /**
     * Gets quoteDiscount
     * 
     * @return Value for quoteDiscount.
     **/
    public BigDecimal getQuoteDiscount() {
        return quoteDiscount;
    }

    /**
     * Sets quoteDiscount
     * 
     * @param quoteDiscount New value for quoteDiscount.
     **/
    public void setQuoteDiscount(BigDecimal quoteDiscount) {
        this.quoteDiscount = quoteDiscount;
    }

    /**
     * Gets quoteDiscountRatio
     * 
     * @return Value for quoteDiscountRatio.
     **/
    public BigDecimal getQuoteDiscountRatio() {
        return quoteDiscountRatio;
    }

    /**
     * Sets quoteDiscountRatio
     * 
     * @param quoteDiscountRatio New value for quoteDiscountRatio.
     **/
    public void setQuoteDiscountRatio(BigDecimal quoteDiscountRatio) {
        this.quoteDiscountRatio = quoteDiscountRatio;
    }

    /**
     * Gets quoteDiscountTime
     * 
     * @return Value for quoteDiscountTime.
     **/
    public Timestamp getQuoteDiscountTime() {
        return quoteDiscountTime;
    }

    /**
     * Sets quoteDiscountTime
     * 
     * @param quoteDiscountTime New value for quoteDiscountTime.
     **/
    public void setQuoteDiscountTime(Timestamp quoteDiscountTime) {
        this.quoteDiscountTime = quoteDiscountTime;
    }

    /**
     * Gets businessOpportunityType
     * 
     * @return Value for businessOpportunityType.
     **/
    public String getBusinessOpportunityType() {
        return businessOpportunityType;
    }

    /**
     * Sets businessOpportunityType
     * 
     * @param businessOpportunityType New value for businessOpportunityType.
     **/
    public void setBusinessOpportunityType(String businessOpportunityType) {
        this.businessOpportunityType = businessOpportunityType;
    }

    /**
     * Gets dealResource
     * 
     * @return Value for dealResource.
     **/
    public String getDealResource() {
        return dealResource;
    }

    /**
     * Sets dealResource
     * 
     * @param dealResource New value for dealResource.
     **/
    public void setDealResource(String dealResource) {
        this.dealResource = dealResource;
    }

    /**
     * Gets discount
     * 
     * @return Value for discount.
     **/
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * Sets discount
     * 
     * @param discount New value for discount.
     **/
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * Gets zhitouFlag
     * 
     * @return Value for zhitouFlag.
     **/
    public Boolean getZhitouFlag() {
        return zhitouFlag;
    }

    /**
     * Sets zhitouFlag
     * 
     * @param zhitouFlag New value for zhitouFlag.
     **/
    public void setZhitouFlag(Boolean zhitouFlag) {
        this.zhitouFlag = zhitouFlag;
    }

    /**
     * Gets zhitouPlanFlag
     * 
     * @return Value for zhitouPlanFlag.
     **/
    public Boolean getZhitouPlanFlag() {
        return zhitouPlanFlag;
    }

    /**
     * Sets zhitouPlanFlag
     * 
     * @param zhitouPlanFlag New value for zhitouPlanFlag.
     **/
    public void setZhitouPlanFlag(Boolean zhitouPlanFlag) {
        this.zhitouPlanFlag = zhitouPlanFlag;
    }

    /**
     * Gets zhitouPlanId
     * 
     * @return Value for zhitouPlanId.
     **/
    public Integer getZhitouPlanId() {
        return zhitouPlanId;
    }

    /**
     * Sets zhitouPlanId
     * 
     * @param zhitouPlanId New value for zhitouPlanId.
     **/
    public void setZhitouPlanId(Integer zhitouPlanId) {
        this.zhitouPlanId = zhitouPlanId;
    }

    /**
     * Gets closeReasonType
     * 
     * @return Value for closeReasonType.
     **/
    public String getCloseReasonType() {
        return closeReasonType;
    }

    /**
     * Sets closeReasonType
     * 
     * @param closeReasonType New value for closeReasonType.
     **/
    public void setCloseReasonType(String closeReasonType) {
        this.closeReasonType = closeReasonType;
    }

    /**
     * Gets pushFlag
     * 
     * @return Value for pushFlag.
     **/
    public Boolean getPushFlag() {
        return pushFlag;
    }

    /**
     * Sets pushFlag
     * 
     * @param pushFlag New value for pushFlag.
     **/
    public void setPushFlag(Boolean pushFlag) {
        this.pushFlag = pushFlag;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Business))
            return false;
        
        Business that = (Business)o;

        if (customerId != that.customerId)
            return false;
        

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        

        if (modifyName != null ? !modifyName.equals(that.modifyName) : that.modifyName != null)
            return false;
        

        if (businessCode != null ? !businessCode.equals(that.businessCode) : that.businessCode != null)
            return false;
        

        if (origin != null ? !origin.equals(that.origin) : that.origin != null)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (level != null ? !level.equals(that.level) : that.level != null)
            return false;
        

        if (industryLevelOne != null ? !industryLevelOne.equals(that.industryLevelOne) : that.industryLevelOne != null)
            return false;
        

        if (industryLevelTwo != null ? !industryLevelTwo.equals(that.industryLevelTwo) : that.industryLevelTwo != null)
            return false;
        

        if (phaseOneCompleteTime != null ? !phaseOneCompleteTime.equals(that.phaseOneCompleteTime) : that.phaseOneCompleteTime != null)
            return false;
        

        if (phaseTwoCompleteTime != null ? !phaseTwoCompleteTime.equals(that.phaseTwoCompleteTime) : that.phaseTwoCompleteTime != null)
            return false;
        

        if (phaseThreeCompleteTime != null ? !phaseThreeCompleteTime.equals(that.phaseThreeCompleteTime) : that.phaseThreeCompleteTime != null)
            return false;
        

        if (phaseFourCompleteTime != null ? !phaseFourCompleteTime.equals(that.phaseFourCompleteTime) : that.phaseFourCompleteTime != null)
            return false;
        

        if (phase != null ? !phase.equals(that.phase) : that.phase != null)
            return false;
        

        if (businessStatus != that.businessStatus)
            return false;
        

        if (restartStatus != null ? !restartStatus.equals(that.restartStatus) : that.restartStatus != null)
            return false;
        

        if (expectAmount != null ? !expectAmount.equals(that.expectAmount) : that.expectAmount != null)
            return false;
        

        if (expectTime != null ? !expectTime.equals(that.expectTime) : that.expectTime != null)
            return false;
        

        if (expectMedia != null ? !expectMedia.equals(that.expectMedia) : that.expectMedia != null)
            return false;
        

        if (expectCity != null ? !expectCity.equals(that.expectCity) : that.expectCity != null)
            return false;
        

        if (expectNum != null ? !expectNum.equals(that.expectNum) : that.expectNum != null)
            return false;
        

        if (expectFrequency != null ? !expectFrequency.equals(that.expectFrequency) : that.expectFrequency != null)
            return false;
        

        if (actualNum != null ? !actualNum.equals(that.actualNum) : that.actualNum != null)
            return false;
        

        if (actualFrequency != null ? !actualFrequency.equals(that.actualFrequency) : that.actualFrequency != null)
            return false;
        

        if (mediaAttitude != null ? !mediaAttitude.equals(that.mediaAttitude) : that.mediaAttitude != null)
            return false;
        

        if (belongUserId != null ? !belongUserId.equals(that.belongUserId) : that.belongUserId != null)
            return false;
        

        if (createUser != null ? !createUser.equals(that.createUser) : that.createUser != null)
            return false;
        

        if (createTime != null ? !createTime.equals(that.createTime) : that.createTime != null)
            return false;
        

        if (updateUser != null ? !updateUser.equals(that.updateUser) : that.updateUser != null)
            return false;
        

        if (updateTime != null ? !updateTime.equals(that.updateTime) : that.updateTime != null)
            return false;
        

        if (remark != null ? !remark.equals(that.remark) : that.remark != null)
            return false;
        

        if (failReason != null ? !failReason.equals(that.failReason) : that.failReason != null)
            return false;
        

        if (closeReason != null ? !closeReason.equals(that.closeReason) : that.closeReason != null)
            return false;
        

        if (acceptProposalFlag != null ? !acceptProposalFlag.equals(that.acceptProposalFlag) : that.acceptProposalFlag != null)
            return false;
        

        if (acceptQuoteFlag != null ? !acceptQuoteFlag.equals(that.acceptQuoteFlag) : that.acceptQuoteFlag != null)
            return false;
        

        if (communicateMaterialFlag != null ? !communicateMaterialFlag.equals(that.communicateMaterialFlag) : that.communicateMaterialFlag != null)
            return false;
        

        if (comfirmPlanFlag != null ? !comfirmPlanFlag.equals(that.comfirmPlanFlag) : that.comfirmPlanFlag != null)
            return false;
        

        if (comfirmMaterialFlag != null ? !comfirmMaterialFlag.equals(that.comfirmMaterialFlag) : that.comfirmMaterialFlag != null)
            return false;
        

        if (jobId != null ? !jobId.equals(that.jobId) : that.jobId != null)
            return false;
        

        if (orgId != null ? !orgId.equals(that.orgId) : that.orgId != null)
            return false;
        

        if (departId != null ? !departId.equals(that.departId) : that.departId != null)
            return false;
        

        if (proposalCustomerFlag != null ? !proposalCustomerFlag.equals(that.proposalCustomerFlag) : that.proposalCustomerFlag != null)
            return false;
        

        if (confirmPointFlag != null ? !confirmPointFlag.equals(that.confirmPointFlag) : that.confirmPointFlag != null)
            return false;
        

        if (preSignContractDate != null ? !preSignContractDate.equals(that.preSignContractDate) : that.preSignContractDate != null)
            return false;
        

        if (contractTakeBackDate != null ? !contractTakeBackDate.equals(that.contractTakeBackDate) : that.contractTakeBackDate != null)
            return false;
        

        if (contractTakeBackFlag != null ? !contractTakeBackFlag.equals(that.contractTakeBackFlag) : that.contractTakeBackFlag != null)
            return false;
        

        if (issueFlag != null ? !issueFlag.equals(that.issueFlag) : that.issueFlag != null)
            return false;
        

        if (businessLevel != null ? !businessLevel.equals(that.businessLevel) : that.businessLevel != null)
            return false;
        

        if (accompanyNum != null ? !accompanyNum.equals(that.accompanyNum) : that.accompanyNum != null)
            return false;
        

        if (syncSys != null ? !syncSys.equals(that.syncSys) : that.syncSys != null)
            return false;
        

        if (dealAmount != null ? !dealAmount.equals(that.dealAmount) : that.dealAmount != null)
            return false;
        

        if (dealTime != null ? !dealTime.equals(that.dealTime) : that.dealTime != null)
            return false;
        

        if (onlineDate != null ? !onlineDate.equals(that.onlineDate) : that.onlineDate != null)
            return false;
        

        if (offlineDate != null ? !offlineDate.equals(that.offlineDate) : that.offlineDate != null)
            return false;
        

        if (closeTime != null ? !closeTime.equals(that.closeTime) : that.closeTime != null)
            return false;
        

        if (businessType != null ? !businessType.equals(that.businessType) : that.businessType != null)
            return false;
        

        if (contractSigningType != null ? !contractSigningType.equals(that.contractSigningType) : that.contractSigningType != null)
            return false;
        

        if (mediaRecognized != that.mediaRecognized)
            return false;
        

        if (hasBudget != that.hasBudget)
            return false;
        

        if (hasLaunchPlan != that.hasLaunchPlan)
            return false;
        

        if (kpVisited != that.kpVisited)
            return false;
        

        if (launchCityPointConfirmed != that.launchCityPointConfirmed)
            return false;
        

        if (materialConfirmed != that.materialConfirmed)
            return false;
        

        if (processingContract != that.processingContract)
            return false;
        

        if (priceDiscount != null ? !priceDiscount.equals(that.priceDiscount) : that.priceDiscount != null)
            return false;
        

        if (priceDiscountRatio != null ? !priceDiscountRatio.equals(that.priceDiscountRatio) : that.priceDiscountRatio != null)
            return false;
        

        if (priceDiscountTime != null ? !priceDiscountTime.equals(that.priceDiscountTime) : that.priceDiscountTime != null)
            return false;
        

        if (quoteDiscount != null ? !quoteDiscount.equals(that.quoteDiscount) : that.quoteDiscount != null)
            return false;
        

        if (quoteDiscountRatio != null ? !quoteDiscountRatio.equals(that.quoteDiscountRatio) : that.quoteDiscountRatio != null)
            return false;
        

        if (quoteDiscountTime != null ? !quoteDiscountTime.equals(that.quoteDiscountTime) : that.quoteDiscountTime != null)
            return false;
        

        if (businessOpportunityType != null ? !businessOpportunityType.equals(that.businessOpportunityType) : that.businessOpportunityType != null)
            return false;
        

        if (dealResource != null ? !dealResource.equals(that.dealResource) : that.dealResource != null)
            return false;
        

        if (discount != null ? !discount.equals(that.discount) : that.discount != null)
            return false;
        

        if (zhitouFlag != null ? !zhitouFlag.equals(that.zhitouFlag) : that.zhitouFlag != null)
            return false;
        

        if (zhitouPlanFlag != null ? !zhitouPlanFlag.equals(that.zhitouPlanFlag) : that.zhitouPlanFlag != null)
            return false;
        

        if (zhitouPlanId != null ? !zhitouPlanId.equals(that.zhitouPlanId) : that.zhitouPlanId != null)
            return false;
        

        if (closeReasonType != null ? !closeReasonType.equals(that.closeReasonType) : that.closeReasonType != null)
            return false;
        

        if (pushFlag != null ? !pushFlag.equals(that.pushFlag) : that.pushFlag != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = customerId;

        res = 31 * res + (name != null ? name.hashCode() : 0);

        res = 31 * res + (modifyName != null ? modifyName.hashCode() : 0);

        res = 31 * res + (businessCode != null ? businessCode.hashCode() : 0);

        res = 31 * res + (origin != null ? origin.hashCode() : 0);

        res = 31 * res + (description != null ? description.hashCode() : 0);

        res = 31 * res + (level != null ? level.hashCode() : 0);

        res = 31 * res + (industryLevelOne != null ? industryLevelOne.hashCode() : 0);

        res = 31 * res + (industryLevelTwo != null ? industryLevelTwo.hashCode() : 0);

        res = 31 * res + (phaseOneCompleteTime != null ? phaseOneCompleteTime.hashCode() : 0);

        res = 31 * res + (phaseTwoCompleteTime != null ? phaseTwoCompleteTime.hashCode() : 0);

        res = 31 * res + (phaseThreeCompleteTime != null ? phaseThreeCompleteTime.hashCode() : 0);

        res = 31 * res + (phaseFourCompleteTime != null ? phaseFourCompleteTime.hashCode() : 0);

        res = 31 * res + (phase != null ? phase.hashCode() : 0);

        res = 31 * res + (int)businessStatus;

        res = 31 * res + (restartStatus != null ? restartStatus.hashCode() : 0);

        res = 31 * res + (expectAmount != null ? expectAmount.hashCode() : 0);

        res = 31 * res + (expectTime != null ? expectTime.hashCode() : 0);

        res = 31 * res + (expectMedia != null ? expectMedia.hashCode() : 0);

        res = 31 * res + (expectCity != null ? expectCity.hashCode() : 0);

        res = 31 * res + (expectNum != null ? expectNum.hashCode() : 0);

        res = 31 * res + (expectFrequency != null ? expectFrequency.hashCode() : 0);

        res = 31 * res + (actualNum != null ? actualNum.hashCode() : 0);

        res = 31 * res + (actualFrequency != null ? actualFrequency.hashCode() : 0);

        res = 31 * res + (mediaAttitude != null ? mediaAttitude.hashCode() : 0);

        res = 31 * res + (belongUserId != null ? belongUserId.hashCode() : 0);

        res = 31 * res + (createUser != null ? createUser.hashCode() : 0);

        res = 31 * res + (createTime != null ? createTime.hashCode() : 0);

        res = 31 * res + (updateUser != null ? updateUser.hashCode() : 0);

        res = 31 * res + (updateTime != null ? updateTime.hashCode() : 0);

        res = 31 * res + (remark != null ? remark.hashCode() : 0);

        res = 31 * res + (failReason != null ? failReason.hashCode() : 0);

        res = 31 * res + (closeReason != null ? closeReason.hashCode() : 0);

        res = 31 * res + (acceptProposalFlag != null ? acceptProposalFlag.hashCode() : 0);

        res = 31 * res + (acceptQuoteFlag != null ? acceptQuoteFlag.hashCode() : 0);

        res = 31 * res + (communicateMaterialFlag != null ? communicateMaterialFlag.hashCode() : 0);

        res = 31 * res + (comfirmPlanFlag != null ? comfirmPlanFlag.hashCode() : 0);

        res = 31 * res + (comfirmMaterialFlag != null ? comfirmMaterialFlag.hashCode() : 0);

        res = 31 * res + (jobId != null ? jobId.hashCode() : 0);

        res = 31 * res + (orgId != null ? orgId.hashCode() : 0);

        res = 31 * res + (departId != null ? departId.hashCode() : 0);

        res = 31 * res + (proposalCustomerFlag != null ? proposalCustomerFlag.hashCode() : 0);

        res = 31 * res + (confirmPointFlag != null ? confirmPointFlag.hashCode() : 0);

        res = 31 * res + (preSignContractDate != null ? preSignContractDate.hashCode() : 0);

        res = 31 * res + (contractTakeBackDate != null ? contractTakeBackDate.hashCode() : 0);

        res = 31 * res + (contractTakeBackFlag != null ? contractTakeBackFlag.hashCode() : 0);

        res = 31 * res + (issueFlag != null ? issueFlag.hashCode() : 0);

        res = 31 * res + (businessLevel != null ? businessLevel.hashCode() : 0);

        res = 31 * res + (accompanyNum != null ? accompanyNum.hashCode() : 0);

        res = 31 * res + (syncSys != null ? syncSys.hashCode() : 0);

        res = 31 * res + (dealAmount != null ? dealAmount.hashCode() : 0);

        res = 31 * res + (dealTime != null ? dealTime.hashCode() : 0);

        res = 31 * res + (onlineDate != null ? onlineDate.hashCode() : 0);

        res = 31 * res + (offlineDate != null ? offlineDate.hashCode() : 0);

        res = 31 * res + (closeTime != null ? closeTime.hashCode() : 0);

        res = 31 * res + (businessType != null ? businessType.hashCode() : 0);

        res = 31 * res + (contractSigningType != null ? contractSigningType.hashCode() : 0);

        res = 31 * res + (mediaRecognized ? 1 : 0);

        res = 31 * res + (hasBudget ? 1 : 0);

        res = 31 * res + (hasLaunchPlan ? 1 : 0);

        res = 31 * res + (kpVisited ? 1 : 0);

        res = 31 * res + (launchCityPointConfirmed ? 1 : 0);

        res = 31 * res + (materialConfirmed ? 1 : 0);

        res = 31 * res + (processingContract ? 1 : 0);

        res = 31 * res + (priceDiscount != null ? priceDiscount.hashCode() : 0);

        res = 31 * res + (priceDiscountRatio != null ? priceDiscountRatio.hashCode() : 0);

        res = 31 * res + (priceDiscountTime != null ? priceDiscountTime.hashCode() : 0);

        res = 31 * res + (quoteDiscount != null ? quoteDiscount.hashCode() : 0);

        res = 31 * res + (quoteDiscountRatio != null ? quoteDiscountRatio.hashCode() : 0);

        res = 31 * res + (quoteDiscountTime != null ? quoteDiscountTime.hashCode() : 0);

        res = 31 * res + (businessOpportunityType != null ? businessOpportunityType.hashCode() : 0);

        res = 31 * res + (dealResource != null ? dealResource.hashCode() : 0);

        res = 31 * res + (discount != null ? discount.hashCode() : 0);

        res = 31 * res + (zhitouFlag != null ? zhitouFlag.hashCode() : 0);

        res = 31 * res + (zhitouPlanFlag != null ? zhitouPlanFlag.hashCode() : 0);

        res = 31 * res + (zhitouPlanId != null ? zhitouPlanId.hashCode() : 0);

        res = 31 * res + (closeReasonType != null ? closeReasonType.hashCode() : 0);

        res = 31 * res + (pushFlag != null ? pushFlag.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Business [" + 
            "customerId=" + customerId + ", " + 
            "name=" + name + ", " + 
            "modifyName=" + modifyName + ", " + 
            "businessCode=" + businessCode + ", " + 
            "origin=" + origin + ", " + 
            "description=" + description + ", " + 
            "level=" + level + ", " + 
            "industryLevelOne=" + industryLevelOne + ", " + 
            "industryLevelTwo=" + industryLevelTwo + ", " + 
            "phaseOneCompleteTime=" + phaseOneCompleteTime + ", " + 
            "phaseTwoCompleteTime=" + phaseTwoCompleteTime + ", " + 
            "phaseThreeCompleteTime=" + phaseThreeCompleteTime + ", " + 
            "phaseFourCompleteTime=" + phaseFourCompleteTime + ", " + 
            "phase=" + phase + ", " + 
            "businessStatus=" + businessStatus + ", " + 
            "restartStatus=" + restartStatus + ", " + 
            "expectAmount=" + expectAmount + ", " + 
            "expectTime=" + expectTime + ", " + 
            "expectMedia=" + expectMedia + ", " + 
            "expectCity=" + expectCity + ", " + 
            "expectNum=" + expectNum + ", " + 
            "expectFrequency=" + expectFrequency + ", " + 
            "actualNum=" + actualNum + ", " + 
            "actualFrequency=" + actualFrequency + ", " + 
            "mediaAttitude=" + mediaAttitude + ", " + 
            "belongUserId=" + belongUserId + ", " + 
            "createUser=" + createUser + ", " + 
            "createTime=" + createTime + ", " + 
            "updateUser=" + updateUser + ", " + 
            "updateTime=" + updateTime + ", " + 
            "remark=" + remark + ", " + 
            "failReason=" + failReason + ", " + 
            "closeReason=" + closeReason + ", " + 
            "acceptProposalFlag=" + acceptProposalFlag + ", " + 
            "acceptQuoteFlag=" + acceptQuoteFlag + ", " + 
            "communicateMaterialFlag=" + communicateMaterialFlag + ", " + 
            "comfirmPlanFlag=" + comfirmPlanFlag + ", " + 
            "comfirmMaterialFlag=" + comfirmMaterialFlag + ", " + 
            "jobId=" + jobId + ", " + 
            "orgId=" + orgId + ", " + 
            "departId=" + departId + ", " + 
            "proposalCustomerFlag=" + proposalCustomerFlag + ", " + 
            "confirmPointFlag=" + confirmPointFlag + ", " + 
            "preSignContractDate=" + preSignContractDate + ", " + 
            "contractTakeBackDate=" + contractTakeBackDate + ", " + 
            "contractTakeBackFlag=" + contractTakeBackFlag + ", " + 
            "issueFlag=" + issueFlag + ", " + 
            "businessLevel=" + businessLevel + ", " + 
            "accompanyNum=" + accompanyNum + ", " + 
            "syncSys=" + syncSys + ", " + 
            "dealAmount=" + dealAmount + ", " + 
            "dealTime=" + dealTime + ", " + 
            "onlineDate=" + onlineDate + ", " + 
            "offlineDate=" + offlineDate + ", " + 
            "closeTime=" + closeTime + ", " + 
            "businessType=" + businessType + ", " + 
            "contractSigningType=" + contractSigningType + ", " + 
            "mediaRecognized=" + mediaRecognized + ", " + 
            "hasBudget=" + hasBudget + ", " + 
            "hasLaunchPlan=" + hasLaunchPlan + ", " + 
            "kpVisited=" + kpVisited + ", " + 
            "launchCityPointConfirmed=" + launchCityPointConfirmed + ", " + 
            "materialConfirmed=" + materialConfirmed + ", " + 
            "processingContract=" + processingContract + ", " + 
            "priceDiscount=" + priceDiscount + ", " + 
            "priceDiscountRatio=" + priceDiscountRatio + ", " + 
            "priceDiscountTime=" + priceDiscountTime + ", " + 
            "quoteDiscount=" + quoteDiscount + ", " + 
            "quoteDiscountRatio=" + quoteDiscountRatio + ", " + 
            "quoteDiscountTime=" + quoteDiscountTime + ", " + 
            "businessOpportunityType=" + businessOpportunityType + ", " + 
            "dealResource=" + dealResource + ", " + 
            "discount=" + discount + ", " + 
            "zhitouFlag=" + zhitouFlag + ", " + 
            "zhitouPlanFlag=" + zhitouPlanFlag + ", " + 
            "zhitouPlanId=" + zhitouPlanId + ", " + 
            "closeReasonType=" + closeReasonType + ", " + 
            "pushFlag=" + pushFlag +
        "]";
    }
}