package model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * BusinessOnlineInfo definition.
 * 
 * This file was generated by Ignite Web Console (10/12/2020, 17:13)
 **/
public class BusinessOnlineInfo implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for businessId. */
    private int businessId;

    /** Value for year. */
    private int year;

    /** Value for month. */
    private int month;

    /** Value for amount. */
    private BigDecimal amount;

    /** Value for createUser. */
    private int createUser;

    /** Value for createTime. */
    private Timestamp createTime;

    /** Value for updateUser. */
    private Integer updateUser;

    /** Value for updateTime. */
    private Timestamp updateTime;

    /** Value for delFlg. */
    private boolean delFlg;

    /** Empty constructor. **/
    public BusinessOnlineInfo() {
        // No-op.
    }

    /** Full constructor. **/
    public BusinessOnlineInfo(int businessId,
        int year,
        int month,
        BigDecimal amount,
        int createUser,
        Timestamp createTime,
        Integer updateUser,
        Timestamp updateTime,
        boolean delFlg) {
        this.businessId = businessId;
        this.year = year;
        this.month = month;
        this.amount = amount;
        this.createUser = createUser;
        this.createTime = createTime;
        this.updateUser = updateUser;
        this.updateTime = updateTime;
        this.delFlg = delFlg;
    }

    /**
     * Gets businessId
     * 
     * @return Value for businessId.
     **/
    public int getBusinessId() {
        return businessId;
    }

    /**
     * Sets businessId
     * 
     * @param businessId New value for businessId.
     **/
    public void setBusinessId(int businessId) {
        this.businessId = businessId;
    }

    /**
     * Gets year
     * 
     * @return Value for year.
     **/
    public int getYear() {
        return year;
    }

    /**
     * Sets year
     * 
     * @param year New value for year.
     **/
    public void setYear(int year) {
        this.year = year;
    }

    /**
     * Gets month
     * 
     * @return Value for month.
     **/
    public int getMonth() {
        return month;
    }

    /**
     * Sets month
     * 
     * @param month New value for month.
     **/
    public void setMonth(int month) {
        this.month = month;
    }

    /**
     * Gets amount
     * 
     * @return Value for amount.
     **/
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets amount
     * 
     * @param amount New value for amount.
     **/
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Gets createUser
     * 
     * @return Value for createUser.
     **/
    public int getCreateUser() {
        return createUser;
    }

    /**
     * Sets createUser
     * 
     * @param createUser New value for createUser.
     **/
    public void setCreateUser(int createUser) {
        this.createUser = createUser;
    }

    /**
     * Gets createTime
     * 
     * @return Value for createTime.
     **/
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * Sets createTime
     * 
     * @param createTime New value for createTime.
     **/
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * Gets updateUser
     * 
     * @return Value for updateUser.
     **/
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * Sets updateUser
     * 
     * @param updateUser New value for updateUser.
     **/
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * Gets updateTime
     * 
     * @return Value for updateTime.
     **/
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets updateTime
     * 
     * @param updateTime New value for updateTime.
     **/
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Gets delFlg
     * 
     * @return Value for delFlg.
     **/
    public boolean getDelFlg() {
        return delFlg;
    }

    /**
     * Sets delFlg
     * 
     * @param delFlg New value for delFlg.
     **/
    public void setDelFlg(boolean delFlg) {
        this.delFlg = delFlg;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof BusinessOnlineInfo))
            return false;
        
        BusinessOnlineInfo that = (BusinessOnlineInfo)o;

        if (businessId != that.businessId)
            return false;
        

        if (year != that.year)
            return false;
        

        if (month != that.month)
            return false;
        

        if (amount != null ? !amount.equals(that.amount) : that.amount != null)
            return false;
        

        if (createUser != that.createUser)
            return false;
        

        if (createTime != null ? !createTime.equals(that.createTime) : that.createTime != null)
            return false;
        

        if (updateUser != null ? !updateUser.equals(that.updateUser) : that.updateUser != null)
            return false;
        

        if (updateTime != null ? !updateTime.equals(that.updateTime) : that.updateTime != null)
            return false;
        

        if (delFlg != that.delFlg)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = businessId;

        res = 31 * res + (year);

        res = 31 * res + (month);

        res = 31 * res + (amount != null ? amount.hashCode() : 0);

        res = 31 * res + (createUser);

        res = 31 * res + (createTime != null ? createTime.hashCode() : 0);

        res = 31 * res + (updateUser != null ? updateUser.hashCode() : 0);

        res = 31 * res + (updateTime != null ? updateTime.hashCode() : 0);

        res = 31 * res + (delFlg ? 1 : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "BusinessOnlineInfo [" + 
            "businessId=" + businessId + ", " + 
            "year=" + year + ", " + 
            "month=" + month + ", " + 
            "amount=" + amount + ", " + 
            "createUser=" + createUser + ", " + 
            "createTime=" + createTime + ", " + 
            "updateUser=" + updateUser + ", " + 
            "updateTime=" + updateTime + ", " + 
            "delFlg=" + delFlg +
        "]";
    }
}