package model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * BusinessSupporter definition.
 * 
 * This file was generated by Ignite Web Console (10/12/2020, 17:13)
 **/
public class BusinessSupporter implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for businessId. */
    private int businessId;

    /** Value for businessName. */
    private String businessName;

    /** Value for customerId. */
    private int customerId;

    /** Value for userId. */
    private Integer userId;

    /** Value for achievementRadio. */
    private BigDecimal achievementRadio;

    /** Value for commissionRadio. */
    private BigDecimal commissionRadio;

    /** Value for supporterStatus. */
    private byte supporterStatus;

    /** Value for delFlg. */
    private boolean delFlg;

    /** Value for createUser. */
    private int createUser;

    /** Value for createTime. */
    private Timestamp createTime;

    /** Value for updateUser. */
    private Integer updateUser;

    /** Value for updateTime. */
    private Timestamp updateTime;

    /** Value for type. */
    private Boolean type;

    /** Value for attachment. */
    private String attachment;

    /** Value for approveUser. */
    private Integer approveUser;

    /** Value for approveName. */
    private String approveName;

    /** Value for approveComment. */
    private String approveComment;

    /** Value for approveTime. */
    private Timestamp approveTime;

    /** Value for deputyGeneralId. */
    private Integer deputyGeneralId;

    /** Value for cityManagerId. */
    private Integer cityManagerId;

    /** Value for regionalManagerId. */
    private Integer regionalManagerId;

    /** Value for departId. */
    private Integer departId;

    /** Value for cityId. */
    private Integer cityId;

    /** Value for regionalId. */
    private Integer regionalId;

    /** Value for saleCenterId. */
    private Integer saleCenterId;

    /** Value for approveStatus. */
    private Byte approveStatus;

    /** Empty constructor. **/
    public BusinessSupporter() {
        // No-op.
    }

    /** Full constructor. **/
    public BusinessSupporter(int businessId,
        String businessName,
        int customerId,
        Integer userId,
        BigDecimal achievementRadio,
        BigDecimal commissionRadio,
        byte supporterStatus,
        boolean delFlg,
        int createUser,
        Timestamp createTime,
        Integer updateUser,
        Timestamp updateTime,
        Boolean type,
        String attachment,
        Integer approveUser,
        String approveName,
        String approveComment,
        Timestamp approveTime,
        Integer deputyGeneralId,
        Integer cityManagerId,
        Integer regionalManagerId,
        Integer departId,
        Integer cityId,
        Integer regionalId,
        Integer saleCenterId,
        Byte approveStatus) {
        this.businessId = businessId;
        this.businessName = businessName;
        this.customerId = customerId;
        this.userId = userId;
        this.achievementRadio = achievementRadio;
        this.commissionRadio = commissionRadio;
        this.supporterStatus = supporterStatus;
        this.delFlg = delFlg;
        this.createUser = createUser;
        this.createTime = createTime;
        this.updateUser = updateUser;
        this.updateTime = updateTime;
        this.type = type;
        this.attachment = attachment;
        this.approveUser = approveUser;
        this.approveName = approveName;
        this.approveComment = approveComment;
        this.approveTime = approveTime;
        this.deputyGeneralId = deputyGeneralId;
        this.cityManagerId = cityManagerId;
        this.regionalManagerId = regionalManagerId;
        this.departId = departId;
        this.cityId = cityId;
        this.regionalId = regionalId;
        this.saleCenterId = saleCenterId;
        this.approveStatus = approveStatus;
    }

    /**
     * Gets businessId
     * 
     * @return Value for businessId.
     **/
    public int getBusinessId() {
        return businessId;
    }

    /**
     * Sets businessId
     * 
     * @param businessId New value for businessId.
     **/
    public void setBusinessId(int businessId) {
        this.businessId = businessId;
    }

    /**
     * Gets businessName
     * 
     * @return Value for businessName.
     **/
    public String getBusinessName() {
        return businessName;
    }

    /**
     * Sets businessName
     * 
     * @param businessName New value for businessName.
     **/
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * Gets customerId
     * 
     * @return Value for customerId.
     **/
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Sets customerId
     * 
     * @param customerId New value for customerId.
     **/
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    /**
     * Gets userId
     * 
     * @return Value for userId.
     **/
    public Integer getUserId() {
        return userId;
    }

    /**
     * Sets userId
     * 
     * @param userId New value for userId.
     **/
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Gets achievementRadio
     * 
     * @return Value for achievementRadio.
     **/
    public BigDecimal getAchievementRadio() {
        return achievementRadio;
    }

    /**
     * Sets achievementRadio
     * 
     * @param achievementRadio New value for achievementRadio.
     **/
    public void setAchievementRadio(BigDecimal achievementRadio) {
        this.achievementRadio = achievementRadio;
    }

    /**
     * Gets commissionRadio
     * 
     * @return Value for commissionRadio.
     **/
    public BigDecimal getCommissionRadio() {
        return commissionRadio;
    }

    /**
     * Sets commissionRadio
     * 
     * @param commissionRadio New value for commissionRadio.
     **/
    public void setCommissionRadio(BigDecimal commissionRadio) {
        this.commissionRadio = commissionRadio;
    }

    /**
     * Gets supporterStatus
     * 
     * @return Value for supporterStatus.
     **/
    public byte getSupporterStatus() {
        return supporterStatus;
    }

    /**
     * Sets supporterStatus
     * 
     * @param supporterStatus New value for supporterStatus.
     **/
    public void setSupporterStatus(byte supporterStatus) {
        this.supporterStatus = supporterStatus;
    }

    /**
     * Gets delFlg
     * 
     * @return Value for delFlg.
     **/
    public boolean getDelFlg() {
        return delFlg;
    }

    /**
     * Sets delFlg
     * 
     * @param delFlg New value for delFlg.
     **/
    public void setDelFlg(boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * Gets createUser
     * 
     * @return Value for createUser.
     **/
    public int getCreateUser() {
        return createUser;
    }

    /**
     * Sets createUser
     * 
     * @param createUser New value for createUser.
     **/
    public void setCreateUser(int createUser) {
        this.createUser = createUser;
    }

    /**
     * Gets createTime
     * 
     * @return Value for createTime.
     **/
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * Sets createTime
     * 
     * @param createTime New value for createTime.
     **/
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * Gets updateUser
     * 
     * @return Value for updateUser.
     **/
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * Sets updateUser
     * 
     * @param updateUser New value for updateUser.
     **/
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * Gets updateTime
     * 
     * @return Value for updateTime.
     **/
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * Sets updateTime
     * 
     * @param updateTime New value for updateTime.
     **/
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Gets type
     * 
     * @return Value for type.
     **/
    public Boolean getType() {
        return type;
    }

    /**
     * Sets type
     * 
     * @param type New value for type.
     **/
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * Gets attachment
     * 
     * @return Value for attachment.
     **/
    public String getAttachment() {
        return attachment;
    }

    /**
     * Sets attachment
     * 
     * @param attachment New value for attachment.
     **/
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    /**
     * Gets approveUser
     * 
     * @return Value for approveUser.
     **/
    public Integer getApproveUser() {
        return approveUser;
    }

    /**
     * Sets approveUser
     * 
     * @param approveUser New value for approveUser.
     **/
    public void setApproveUser(Integer approveUser) {
        this.approveUser = approveUser;
    }

    /**
     * Gets approveName
     * 
     * @return Value for approveName.
     **/
    public String getApproveName() {
        return approveName;
    }

    /**
     * Sets approveName
     * 
     * @param approveName New value for approveName.
     **/
    public void setApproveName(String approveName) {
        this.approveName = approveName;
    }

    /**
     * Gets approveComment
     * 
     * @return Value for approveComment.
     **/
    public String getApproveComment() {
        return approveComment;
    }

    /**
     * Sets approveComment
     * 
     * @param approveComment New value for approveComment.
     **/
    public void setApproveComment(String approveComment) {
        this.approveComment = approveComment;
    }

    /**
     * Gets approveTime
     * 
     * @return Value for approveTime.
     **/
    public Timestamp getApproveTime() {
        return approveTime;
    }

    /**
     * Sets approveTime
     * 
     * @param approveTime New value for approveTime.
     **/
    public void setApproveTime(Timestamp approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * Gets deputyGeneralId
     * 
     * @return Value for deputyGeneralId.
     **/
    public Integer getDeputyGeneralId() {
        return deputyGeneralId;
    }

    /**
     * Sets deputyGeneralId
     * 
     * @param deputyGeneralId New value for deputyGeneralId.
     **/
    public void setDeputyGeneralId(Integer deputyGeneralId) {
        this.deputyGeneralId = deputyGeneralId;
    }

    /**
     * Gets cityManagerId
     * 
     * @return Value for cityManagerId.
     **/
    public Integer getCityManagerId() {
        return cityManagerId;
    }

    /**
     * Sets cityManagerId
     * 
     * @param cityManagerId New value for cityManagerId.
     **/
    public void setCityManagerId(Integer cityManagerId) {
        this.cityManagerId = cityManagerId;
    }

    /**
     * Gets regionalManagerId
     * 
     * @return Value for regionalManagerId.
     **/
    public Integer getRegionalManagerId() {
        return regionalManagerId;
    }

    /**
     * Sets regionalManagerId
     * 
     * @param regionalManagerId New value for regionalManagerId.
     **/
    public void setRegionalManagerId(Integer regionalManagerId) {
        this.regionalManagerId = regionalManagerId;
    }

    /**
     * Gets departId
     * 
     * @return Value for departId.
     **/
    public Integer getDepartId() {
        return departId;
    }

    /**
     * Sets departId
     * 
     * @param departId New value for departId.
     **/
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * Gets cityId
     * 
     * @return Value for cityId.
     **/
    public Integer getCityId() {
        return cityId;
    }

    /**
     * Sets cityId
     * 
     * @param cityId New value for cityId.
     **/
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * Gets regionalId
     * 
     * @return Value for regionalId.
     **/
    public Integer getRegionalId() {
        return regionalId;
    }

    /**
     * Sets regionalId
     * 
     * @param regionalId New value for regionalId.
     **/
    public void setRegionalId(Integer regionalId) {
        this.regionalId = regionalId;
    }

    /**
     * Gets saleCenterId
     * 
     * @return Value for saleCenterId.
     **/
    public Integer getSaleCenterId() {
        return saleCenterId;
    }

    /**
     * Sets saleCenterId
     * 
     * @param saleCenterId New value for saleCenterId.
     **/
    public void setSaleCenterId(Integer saleCenterId) {
        this.saleCenterId = saleCenterId;
    }

    /**
     * Gets approveStatus
     * 
     * @return Value for approveStatus.
     **/
    public Byte getApproveStatus() {
        return approveStatus;
    }

    /**
     * Sets approveStatus
     * 
     * @param approveStatus New value for approveStatus.
     **/
    public void setApproveStatus(Byte approveStatus) {
        this.approveStatus = approveStatus;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof BusinessSupporter))
            return false;
        
        BusinessSupporter that = (BusinessSupporter)o;

        if (businessId != that.businessId)
            return false;
        

        if (businessName != null ? !businessName.equals(that.businessName) : that.businessName != null)
            return false;
        

        if (customerId != that.customerId)
            return false;
        

        if (userId != null ? !userId.equals(that.userId) : that.userId != null)
            return false;
        

        if (achievementRadio != null ? !achievementRadio.equals(that.achievementRadio) : that.achievementRadio != null)
            return false;
        

        if (commissionRadio != null ? !commissionRadio.equals(that.commissionRadio) : that.commissionRadio != null)
            return false;
        

        if (supporterStatus != that.supporterStatus)
            return false;
        

        if (delFlg != that.delFlg)
            return false;
        

        if (createUser != that.createUser)
            return false;
        

        if (createTime != null ? !createTime.equals(that.createTime) : that.createTime != null)
            return false;
        

        if (updateUser != null ? !updateUser.equals(that.updateUser) : that.updateUser != null)
            return false;
        

        if (updateTime != null ? !updateTime.equals(that.updateTime) : that.updateTime != null)
            return false;
        

        if (type != null ? !type.equals(that.type) : that.type != null)
            return false;
        

        if (attachment != null ? !attachment.equals(that.attachment) : that.attachment != null)
            return false;
        

        if (approveUser != null ? !approveUser.equals(that.approveUser) : that.approveUser != null)
            return false;
        

        if (approveName != null ? !approveName.equals(that.approveName) : that.approveName != null)
            return false;
        

        if (approveComment != null ? !approveComment.equals(that.approveComment) : that.approveComment != null)
            return false;
        

        if (approveTime != null ? !approveTime.equals(that.approveTime) : that.approveTime != null)
            return false;
        

        if (deputyGeneralId != null ? !deputyGeneralId.equals(that.deputyGeneralId) : that.deputyGeneralId != null)
            return false;
        

        if (cityManagerId != null ? !cityManagerId.equals(that.cityManagerId) : that.cityManagerId != null)
            return false;
        

        if (regionalManagerId != null ? !regionalManagerId.equals(that.regionalManagerId) : that.regionalManagerId != null)
            return false;
        

        if (departId != null ? !departId.equals(that.departId) : that.departId != null)
            return false;
        

        if (cityId != null ? !cityId.equals(that.cityId) : that.cityId != null)
            return false;
        

        if (regionalId != null ? !regionalId.equals(that.regionalId) : that.regionalId != null)
            return false;
        

        if (saleCenterId != null ? !saleCenterId.equals(that.saleCenterId) : that.saleCenterId != null)
            return false;
        

        if (approveStatus != null ? !approveStatus.equals(that.approveStatus) : that.approveStatus != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = businessId;

        res = 31 * res + (businessName != null ? businessName.hashCode() : 0);

        res = 31 * res + (customerId);

        res = 31 * res + (userId != null ? userId.hashCode() : 0);

        res = 31 * res + (achievementRadio != null ? achievementRadio.hashCode() : 0);

        res = 31 * res + (commissionRadio != null ? commissionRadio.hashCode() : 0);

        res = 31 * res + (int)supporterStatus;

        res = 31 * res + (delFlg ? 1 : 0);

        res = 31 * res + (createUser);

        res = 31 * res + (createTime != null ? createTime.hashCode() : 0);

        res = 31 * res + (updateUser != null ? updateUser.hashCode() : 0);

        res = 31 * res + (updateTime != null ? updateTime.hashCode() : 0);

        res = 31 * res + (type != null ? type.hashCode() : 0);

        res = 31 * res + (attachment != null ? attachment.hashCode() : 0);

        res = 31 * res + (approveUser != null ? approveUser.hashCode() : 0);

        res = 31 * res + (approveName != null ? approveName.hashCode() : 0);

        res = 31 * res + (approveComment != null ? approveComment.hashCode() : 0);

        res = 31 * res + (approveTime != null ? approveTime.hashCode() : 0);

        res = 31 * res + (deputyGeneralId != null ? deputyGeneralId.hashCode() : 0);

        res = 31 * res + (cityManagerId != null ? cityManagerId.hashCode() : 0);

        res = 31 * res + (regionalManagerId != null ? regionalManagerId.hashCode() : 0);

        res = 31 * res + (departId != null ? departId.hashCode() : 0);

        res = 31 * res + (cityId != null ? cityId.hashCode() : 0);

        res = 31 * res + (regionalId != null ? regionalId.hashCode() : 0);

        res = 31 * res + (saleCenterId != null ? saleCenterId.hashCode() : 0);

        res = 31 * res + (approveStatus != null ? approveStatus.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "BusinessSupporter [" + 
            "businessId=" + businessId + ", " + 
            "businessName=" + businessName + ", " + 
            "customerId=" + customerId + ", " + 
            "userId=" + userId + ", " + 
            "achievementRadio=" + achievementRadio + ", " + 
            "commissionRadio=" + commissionRadio + ", " + 
            "supporterStatus=" + supporterStatus + ", " + 
            "delFlg=" + delFlg + ", " + 
            "createUser=" + createUser + ", " + 
            "createTime=" + createTime + ", " + 
            "updateUser=" + updateUser + ", " + 
            "updateTime=" + updateTime + ", " + 
            "type=" + type + ", " + 
            "attachment=" + attachment + ", " + 
            "approveUser=" + approveUser + ", " + 
            "approveName=" + approveName + ", " + 
            "approveComment=" + approveComment + ", " + 
            "approveTime=" + approveTime + ", " + 
            "deputyGeneralId=" + deputyGeneralId + ", " + 
            "cityManagerId=" + cityManagerId + ", " + 
            "regionalManagerId=" + regionalManagerId + ", " + 
            "departId=" + departId + ", " + 
            "cityId=" + cityId + ", " + 
            "regionalId=" + regionalId + ", " + 
            "saleCenterId=" + saleCenterId + ", " + 
            "approveStatus=" + approveStatus +
        "]";
    }
}