package model;

import java.io.Serializable;

/**
 * CrmDepartResult definition.
 * 
 * This file was generated by Ignite Web Console (10/14/2020, 16:49)
 **/
public class CrmDepartResult implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for onlineBusinessCount. */
    private Integer onlineBusinessCount;

    /** Value for onlineBusinessCustomerCount. */
    private Integer onlineBusinessCustomerCount;

    /** Value for onlineBusinessAmount. */
    private String onlineBusinessAmount;

    /** Empty constructor. **/
    public CrmDepartResult() {
        // No-op.
    }

    /** Full constructor. **/
    public CrmDepartResult(Integer onlineBusinessCount,
                           Integer onlineBusinessCustomerCount,
                           String onlineBusinessAmount) {
        this.onlineBusinessCount = onlineBusinessCount;
        this.onlineBusinessCustomerCount = onlineBusinessCustomerCount;
        this.onlineBusinessAmount = onlineBusinessAmount;
    }

    /**
     * Gets onlineBusinessCount
     * 
     * @return Value for onlineBusinessCount.
     **/
    public Integer getOnlineBusinessCount() {
        return onlineBusinessCount;
    }

    /**
     * Sets onlineBusinessCount
     * 
     * @param onlineBusinessCount New value for onlineBusinessCount.
     **/
    public void setOnlineBusinessCount(Integer onlineBusinessCount) {
        this.onlineBusinessCount = onlineBusinessCount;
    }

    /**
     * Gets onlineBusinessCustomerCount
     * 
     * @return Value for onlineBusinessCustomerCount.
     **/
    public Integer getOnlineBusinessCustomerCount() {
        return onlineBusinessCustomerCount;
    }

    /**
     * Sets onlineBusinessCustomerCount
     * 
     * @param onlineBusinessCustomerCount New value for onlineBusinessCustomerCount.
     **/
    public void setOnlineBusinessCustomerCount(Integer onlineBusinessCustomerCount) {
        this.onlineBusinessCustomerCount = onlineBusinessCustomerCount;
    }

    /**
     * Gets onlineBusinessAmount
     * 
     * @return Value for onlineBusinessAmount.
     **/
    public String getOnlineBusinessAmount() {
        return onlineBusinessAmount;
    }

    /**
     * Sets onlineBusinessAmount
     * 
     * @param onlineBusinessAmount New value for onlineBusinessAmount.
     **/
    public void setOnlineBusinessAmount(String onlineBusinessAmount) {
        this.onlineBusinessAmount = onlineBusinessAmount;
    }

    /** {@inheritDoc} **/
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof CrmDepartResult))
            return false;
        
        CrmDepartResult that = (CrmDepartResult)o;

        if (onlineBusinessCount != null ? !onlineBusinessCount.equals(that.onlineBusinessCount) : that.onlineBusinessCount != null)
            return false;
        

        if (onlineBusinessCustomerCount != null ? !onlineBusinessCustomerCount.equals(that.onlineBusinessCustomerCount) : that.onlineBusinessCustomerCount != null)
            return false;
        

        if (onlineBusinessAmount != null ? !onlineBusinessAmount.equals(that.onlineBusinessAmount) : that.onlineBusinessAmount != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override
    public int hashCode() {
        int res = onlineBusinessCount != null ? onlineBusinessCount.hashCode() : 0;

        res = 31 * res + (onlineBusinessCustomerCount != null ? onlineBusinessCustomerCount.hashCode() : 0);

        res = 31 * res + (onlineBusinessAmount != null ? onlineBusinessAmount.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override
    public String toString() {
        return "CrmDepartResult [" + 
            "onlineBusinessCount=" + onlineBusinessCount + ", " + 
            "onlineBusinessCustomerCount=" + onlineBusinessCustomerCount + ", " + 
            "onlineBusinessAmount=" + onlineBusinessAmount +
        "]";
    }
}