package model;

import java.io.Serializable;

/**
 * CrmResult definition.
 * 
 * This file was generated by Ignite Web Console (10/12/2020, 17:13)
 **/
public class CrmResult implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for year. */
    private Integer year;

    /** Value for month. */
    private Integer month;

    /** Value for onlineBusinessCount. */
    private Integer onlineBusinessCount;

    /** Value for onlineBusinessCustomerCount. */
    private Integer onlineBusinessCustomerCount;

    /** Value for onlineBusinessAmount. */
    private String onlineBusinessAmount;

    /** Empty constructor. **/
    public CrmResult() {
        // No-op.
    }

    /** Full constructor. **/
    public CrmResult(Integer year,
        Integer month,
        Integer onlineBusinessCount,
        Integer onlineBusinessCustomerCount,
        String onlineBusinessAmount) {
        this.year = year;
        this.month = month;
        this.onlineBusinessCount = onlineBusinessCount;
        this.onlineBusinessCustomerCount = onlineBusinessCustomerCount;
        this.onlineBusinessAmount = onlineBusinessAmount;
    }

    /**
     * Gets year
     * 
     * @return Value for year.
     **/
    public Integer getYear() {
        return year;
    }

    /**
     * Sets year
     * 
     * @param year New value for year.
     **/
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * Gets month
     * 
     * @return Value for month.
     **/
    public Integer getMonth() {
        return month;
    }

    /**
     * Sets month
     * 
     * @param month New value for month.
     **/
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * Gets onlineBusinessCount
     * 
     * @return Value for onlineBusinessCount.
     **/
    public Integer getOnlineBusinessCount() {
        return onlineBusinessCount;
    }

    /**
     * Sets onlineBusinessCount
     * 
     * @param onlineBusinessCount New value for onlineBusinessCount.
     **/
    public void setOnlineBusinessCount(Integer onlineBusinessCount) {
        this.onlineBusinessCount = onlineBusinessCount;
    }

    /**
     * Gets onlineBusinessCustomerCount
     * 
     * @return Value for onlineBusinessCustomerCount.
     **/
    public Integer getOnlineBusinessCustomerCount() {
        return onlineBusinessCustomerCount;
    }

    /**
     * Sets onlineBusinessCustomerCount
     * 
     * @param onlineBusinessCustomerCount New value for onlineBusinessCustomerCount.
     **/
    public void setOnlineBusinessCustomerCount(Integer onlineBusinessCustomerCount) {
        this.onlineBusinessCustomerCount = onlineBusinessCustomerCount;
    }

    /**
     * Gets onlineBusinessAmount
     * 
     * @return Value for onlineBusinessAmount.
     **/
    public String getOnlineBusinessAmount() {
        return onlineBusinessAmount;
    }

    /**
     * Sets onlineBusinessAmount
     * 
     * @param onlineBusinessAmount New value for onlineBusinessAmount.
     **/
    public void setOnlineBusinessAmount(String onlineBusinessAmount) {
        this.onlineBusinessAmount = onlineBusinessAmount;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof CrmResult))
            return false;
        
        CrmResult that = (CrmResult)o;

        if (year != null ? !year.equals(that.year) : that.year != null)
            return false;
        

        if (month != null ? !month.equals(that.month) : that.month != null)
            return false;
        

        if (onlineBusinessCount != null ? !onlineBusinessCount.equals(that.onlineBusinessCount) : that.onlineBusinessCount != null)
            return false;
        

        if (onlineBusinessCustomerCount != null ? !onlineBusinessCustomerCount.equals(that.onlineBusinessCustomerCount) : that.onlineBusinessCustomerCount != null)
            return false;
        

        if (onlineBusinessAmount != null ? !onlineBusinessAmount.equals(that.onlineBusinessAmount) : that.onlineBusinessAmount != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = year != null ? year.hashCode() : 0;

        res = 31 * res + (month != null ? month.hashCode() : 0);

        res = 31 * res + (onlineBusinessCount != null ? onlineBusinessCount.hashCode() : 0);

        res = 31 * res + (onlineBusinessCustomerCount != null ? onlineBusinessCustomerCount.hashCode() : 0);

        res = 31 * res + (onlineBusinessAmount != null ? onlineBusinessAmount.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "CrmResult [" + 
            "year=" + year + ", " + 
            "month=" + month + ", " + 
            "onlineBusinessCount=" + onlineBusinessCount + ", " + 
            "onlineBusinessCustomerCount=" + onlineBusinessCustomerCount + ", " + 
            "onlineBusinessAmount=" + onlineBusinessAmount +
        "]";
    }
}