package load;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (10/12/2020, 17:13) **/
public class LoadCaches {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        try (Ignite ignite = Ignition.start("ImportedCluster2-client.xml")) {
            System.out.println(">>> Loading caches...");

            System.out.println(">>> Loading cache: BaseDepartmentCache");
            ignite.cache("CRMBASEDEPT").loadCache(null);

            System.out.println(">>> Loading cache: BaseJobCache");
            ignite.cache("CRMBASEJOB").loadCache(null);

            System.out.println(">>> Loading cache: BaseUserCache");
            ignite.cache("CRMBASEUSER").loadCache(null);

            System.out.println(">>> Loading cache: BaseUserJobCache");
            ignite.cache("CRMBASEUJ").loadCache(null);

            System.out.println(">>> Loading cache: BusinessCache");
            ignite.cache("CRMBUSINESS").loadCache(null);

            System.out.println(">>> Loading cache: BusinessOnlineInfoCache");
            ignite.cache("CRMBOI").loadCache(null);

            System.out.println(">>> Loading cache: BusinessSupporterCache");
            ignite.cache("CRMBS").loadCache(null);

            System.out.println(">>> Loading cache: CrmResultCache");
            ignite.cache("CRMRESULT").loadCache(null);

            System.out.println(">>> Loading cache: CrmDepartResultCache");
            ignite.cache("CRMDEPTRESULT").loadCache(null);

            System.out.println(">>> All caches loaded!");
        }
    }
}